import { chromium } from 'playwright'
const t = await chromium.launch({ args:['--ignore-certificate-errors'] })
for (const [w,h,ad] of [[390,844,'telefon'],[1366,900,'masaustu']]) {
  const ctx = await t.newContext({ viewport:{width:w,height:h}, deviceScaleFactor:2, ignoreHTTPSErrors:true })
  const s = await ctx.newPage()
  s.on('console', m => { if (m.type()==='error') console.log(`[${ad}]`, m.text().slice(0,120)) })
  await s.goto('http://127.0.0.1:4173/', { waitUntil:'networkidle' })
  await s.getByRole('button', { name:/giriş/i }).first().click().catch(()=>{})
  await s.waitForTimeout(600)
  await s.locator('input[type=email]').fill('test.koc@khkocluk.com')
  await s.locator('input[type=password]').fill('Test2026!ux')
  await s.locator('form button[type=submit], button:has-text("Giriş yap")').last().click()
  await s.waitForTimeout(4000)
  await s.getByRole('button', { name:'Öğrenciler' }).first().click().catch(()=>{})
  await s.waitForTimeout(1500)
  await s.getByText('Deniz Yüksel').first().click().catch(()=>{})
  await s.waitForTimeout(2000)
  await s.getByRole('button', { name:'Denemeler' }).first().click().catch(()=>{})
  await s.waitForTimeout(1500)
  const ekle = s.getByRole('button', { name:/Deneme ekle|Ekle/ }).first()
  await ekle.click().catch(()=>console.log(`[${ad}] ekle düğmesi yok`))
  await s.waitForTimeout(1200)
  console.log(`[${ad}] karne düğmesi:`, await s.locator('text=Karne yükle').count())
  await s.screenshot({ path:`/tmp/karne-${ad}.png`, fullPage:true })
  await ctx.close()
}
await t.close()
