"""Konu bankaları. Her satır: (başlık, kanca). Kanca = videonun ilk 2 saniyesinde
ekranda duran cümle; kapak da budur (ilk kare kuralı)."""

# Pazartesi — HAFTANIN PLANI (öğrenci)
PLAN = [
 ("Haftayı üç işle başlat", "Bu hafta her şeyi yapmayacaksın. Üç şeyi yapacaksın."),
 ("Plan kâğıtta değil, takvimde", "Yazdığın plan değil, saat verdiğin plan çalışır."),
 ("Pazartesi sendromu", "Pazartesi zor değil. Pazar akşamı plan yapmamak zor."),
 ("En zor dersi sabaha koy", "Enerjin en yüksekken en çok kaçtığın dersi çöz."),
 ("25 dakikalık blok", "2 saat oturmak yerine 4 kere 25 dakika dene."),
 ("Boş gün planla", "Haftada bir gün boş bırakmayan, iki gün boşa gider."),
 ("Plan bozulursa ne olur", "Plan bozulur. Önemli olan ertesi gün nereden devam ettiğin."),
 ("Soru sayısı mı, saat mi?", "‘5 saat çalıştım’ değil, ‘120 soru, 14 yanlış’ de."),
 ("Okul sonrası ilk saat", "Eve gelince ilk saat: yemek ve 20 dakika hiçbir şey."),
 ("Tekrar günü", "Yeni konu değil. Bu hafta geçen haftayı tekrar et."),
 ("Telefon başka odada", "Telefon masadaysa, aklın da masada değil."),
 ("Haftalık tek hedef", "Bu haftanın tek cümlelik hedefini yaz. Tek cümle."),
 ("Zayıf konu listesi", "En zayıf 3 konunu biliyor musun? Adıyla söyle."),
 ("Çalışma saatini sabitle", "Her gün aynı saatte masaya otur. Gerisi kolay."),
 ("Yorgunluk haftası", "Yorgunsan plan küçülür, iptal olmaz."),
 ("Deneme haftası planı", "Deneme olan hafta yeni konu açma."),
 ("Plan ile program farkı", "Program okulun. Plan senin. İkisini karıştırma."),
 ("Kırmızı kutular", "Yapılmayan iş silinmez. Taşınır ya da küçülür."),
 ("Sabah 20 dakika", "Okuldan önce 20 dakika paragraf. Günün en kolay kazancı."),
 ("Yatmadan 10 dakika", "Yatmadan önce 10 dakika: bugün yanlış yaptığın 3 soru."),
 ("Konu bitirme yanılgısı", "Konu bitmez. Soru çözdükçe biter."),
 ("Haftalık net hedefi", "Bu hafta +1 net. Sadece bir. Ama gerçek."),
 ("Ders geçişleri", "Sayısaldan sonra sözel: beyin dinlenir, sen çalışırsın."),
 ("Uyku saati planın parçası", "Uyku saatin yoksa, planın da yok."),
 ("Çalışma yerini değiştir", "Hep yatakta mı çalışıyorsun? Sorun orada olabilir."),
 ("Biriken ödev", "Okul ödevi birikti mi? Önce onu bitir, sonra plana dön."),
 ("Hafta ortası kontrolü", "Çarşamba akşamı 5 dakikalık kontrol haftayı kurtarır."),
 ("Mola planlanır", "Mola kaçamak değil, planın bir satırıdır."),
 ("Kolay işle başla", "Masaya oturunca ilk iş: 10 kolay soru. Motor ısınsın."),
 ("Plan paylaşılır", "Planını birine söyle. Sadece söylemek bile işe yarar."),
 ("Tatil sonrası dönüş", "Tatilden sonra ilk hafta yarım hız. Bilerek."),
 ("Her şey acil değil", "Her ders aynı anda acil değil. Sıra koy."),
 ("Soru bankası seçimi", "Üç kitap yarım bitmesin. Bir kitap bitsin."),
 ("Kaynak bitirme", "Bu ay bitireceğin tek kaynağı seç."),
 ("Plan şişmesi", "Plana her gün bir şey ekliyorsan, plan değil liste yapıyorsun."),
 ("Sabah mı, akşam mı?", "Sen sabah insanı mısın? Planını ona göre kur."),
 ("Hafta sonu yükü", "Hafta içi kaçanı hafta sonuna yığma. Hafta sonu çöker."),
 ("İlk 3 gün kuralı", "Yeni plan ilk 3 gün zor. 4. gün alışkanlık başlar."),
 ("Kopya plan", "Başkasının planı sana uymaz. Onun saati senin saatin değil."),
 ("Günlük minimum", "Kötü günün bile minimumu olsun: 20 soru."),
 ("Haftanın ölçüsü", "Pazar akşamı sor: kaç iş vardı, kaçı bitti?"),
 ("Yeni ay, sade plan", "Ay başı: planı büyütme, temizle."),
 ("Deneme sonrası plan", "Denemede çıkan 3 eksik, bu haftanın planıdır."),
 ("Kış saatleri", "Hava 17:30'da kararıyor. Planı ışığa göre kur."),
 ("Okul yoğun haftası", "Yazılı haftası: YKS planı durmaz, küçülür."),
 ("Sınavdan geriye plan", "Sınavdan geriye say: bu hafta hangi dilimdesin?"),
 ("Plan çizelgesi", "Haftayı bir kâğıda sığdır. Sığmıyorsa fazla."),
 ("Tek sayfa hafta", "Bu hafta tek sayfada: 5 gün, 3 iş, 1 deneme."),
 ("Ritmi koru", "Motivasyon gelir gider. Ritim kalır."),
 ("Yaz planı", "Yaz tatili dinlenmek için. Ama her gün 1 saat kural."),
]

# Salı — DERS TAKTİĞİ: (ders, başlık, kanca)
TAKTIK = [
 ("TYT Türkçe", "Paragrafta önce soru kökü", "Paragrafı okumadan önce soruyu oku. 20 saniye kazanırsın."),
 ("TYT Matematik", "Problemlerde tabloyu çiz", "Yaş problemi mi? Önce tablo. Sonra denklem."),
 ("Geometri", "Açıyı çizime yaz", "Soruda verilen her açıyı çizimin üstüne yaz. Yarısı çözülür."),
 ("Fizik", "Birimle kontrol et", "Cevabın birimi tutmuyorsa, cevap da tutmuyor."),
 ("Kimya", "Mol köprüsü", "Kimyada her şey mole çıkar, molden iner."),
 ("Biyoloji", "Şemayla çalış", "Biyolojiyi oku değil, çiz. Hücre bölünmesini 3 kere çiz."),
 ("Tarih", "Zaman çizelgesi", "Tarihi olay olarak değil, sıra olarak ezberle."),
 ("Coğrafya", "Harita üstünde çalış", "Coğrafya sorusu haritada doğar. Atlası aç."),
 ("LGS Matematik", "Yeni nesil soru okuma", "Yeni nesil soruda ilk iş: sorulanın altını çiz."),
 ("TYT Türkçe", "Dil bilgisinde eleme", "Emin olmadığın şıkkı değil, kesin yanlışı ele."),
 ("TYT Matematik", "Sayı basamakları", "Basamak sorusunda harfleri sayıya çevir, gerisi aritmetik."),
 ("AYT Matematik", "Türevde grafik oku", "Türev sorusu grafikle geliyorsa, işaret tablosu yap."),
 ("Edebiyat", "Dönem–sanatçı eşleşmesi", "Edebiyat ezber değil eşleştirme. Tablo kur."),
 ("Fizik", "Serbest cisim diyagramı", "Kuvvet sorusunda formülden önce oklar."),
 ("Kimya", "Periyodik tabloda yön", "Sağa ve yukarı: elektronegatiflik artar. Bu kadar."),
 ("LGS Fen", "Deney sorularında değişken", "Deney sorusunda ilk soru: ne değişti, ne sabit?"),
 ("Biyoloji", "Tuzak kelimeler", "‘Yalnızca’ ve ‘kesinlikle’ gördüysen dur."),
 ("TYT Türkçe", "Anlatım bozukluğu", "Cümleyi sesli oku. Kulak, kuraldan hızlı yakalar."),
 ("Geometri", "Yardımcı çizgi", "Takıldın mı? Bir yardımcı çizgi çek: dikme ya da paralel."),
 ("TYT Matematik", "Oran orantı", "Oran sorusunda k kullan. Karmaşa biter."),
 ("Tarih", "Neden–sonuç zinciri", "Tarih sorusu ‘neden’ sorar. Olayı değil sebebi bil."),
 ("Felsefe", "Filozof–kavram eşlemesi", "Felsefede kavramı filozofun ağzından cümleyle ezberle."),
 ("AYT Matematik", "Limitte belirsizlik", "0/0 gördüysen çarpanlara ayır. İlk refleks bu."),
 ("LGS Türkçe", "Grafik yorumlama", "Grafik sorusunda önce eksenleri oku, sonra çizgiyi."),
 ("Fizik", "Elektrikte eşdeğer direnç", "Devreyi yeniden çiz. Karışık devre sadeleşir."),
 ("Kimya", "Tepkime denkleştirme", "Önce en karmaşık molekülden başla."),
 ("Biyoloji", "Kalıtımda çaprazlama", "Çaprazlamada tablo kur, tahmin yürütme."),
 ("Coğrafya", "İklim grafikleri", "İklim grafiğinde önce yağış rejimine bak."),
 ("TYT Türkçe", "Sözcükte anlam", "Sözcüğü cümleden çıkar, yerine başka kelime koy."),
 ("TYT Matematik", "Mutlak değer", "Mutlak değerde iki durum yaz. Hep iki."),
 ("LGS İngilizce", "Diyalog sorusu", "Diyalogda son cümle cevabın ipucunu taşır."),
 ("Geometri", "Üçgende benzerlik", "Paralel doğru gördüysen benzerlik ara."),
 ("AYT Matematik", "İntegral alan", "Alan sorusunda önce grafik, sonra integral."),
 ("Edebiyat", "Şiir bilgisi", "Ölçü sorusunda heceleri parmakla değil kalemle say."),
 ("Fizik", "Grafik okuma", "Hız–zaman grafiğinde alan yol, eğim ivmedir."),
 ("Kimya", "Asit–baz", "pH sorusunda önce ne kadar H⁺ var, onu bul."),
 ("Biyoloji", "Sistemler", "Sistem sorularını organ değil görevle çalış."),
 ("Tarih", "İnkılap tarihi kronolojisi", "Kongrelerin sırasını hikâye gibi anlat."),
 ("LGS Matematik", "Çarpanlar ve katlar", "EBOB mu EKOK mu? Parçalamak mı, birleştirmek mi?"),
 ("TYT Türkçe", "Paragrafta ana düşünce", "Ana düşünce çoğu zaman ilk ya da son cümlede."),
 ("TYT Matematik", "Hız problemleri", "Hız sorusunda şekil çiz. Araçlar kâğıtta yürüsün."),
 ("Coğrafya", "Nüfus piramitleri", "Piramidin tabanı geniş mi? Genç nüfus."),
 ("Fizik", "Optik", "Aynada ışın çiz: en az iki ışın, her zaman."),
 ("Kimya", "Organik adlandırma", "En uzun zinciri bul, gerisi ek."),
 ("Biyoloji", "Ekoloji", "Besin zincirinde enerji azalır, zehir artar."),
 ("AYT Matematik", "Trigonometri", "Birim çemberi ezberleme, her seferinde çiz."),
 ("LGS Fen", "Basınç", "Basınçta ilk soru: katı mı, sıvı mı, gaz mı?"),
 ("TYT Türkçe", "Yazım kuralları", "‘de’ ayrı mı bitişik mi? Çıkar, anlam bozulmuyorsa ayrı."),
 ("Geometri", "Çemberde açılar", "Çevre açı, merkez açının yarısı. Tek kural."),
 ("Tarih", "Osmanlı dönemleri", "Osmanlı'yı dönem dönem çalış: kuruluş, yükseliş, duraklama."),
]

# Çarşamba — AYNI HAFTA (koç–öğrenci yazışması; marka serisi). (başlık, öğrencinin mesajı)
AYNI_HAFTA = [
 ("Dün hiç çalışmadım", "Hocam dün hiç çalışmadım. Bugün iki katı mı yapayım?"),
 ("Denemede düştüm", "Hocam denemede 8 net düştüm. Her şey boşa mı gitti?"),
 ("Arkadaşım benden iyi", "Sınıfta herkes benden çok çalışıyor gibi."),
 ("Uyuyamıyorum", "Gece 2'ye kadar uyuyamıyorum, sabah kalkamıyorum."),
 ("Matematik korkusu", "Matematiğe oturunca elim kolum bağlanıyor."),
 ("Telefonu bırakamıyorum", "Bir bakayım diyorum, 1 saat geçiyor."),
 ("Ailem baskı yapıyor", "Annem her akşam kaç soru çözdüğümü soruyor."),
 ("Okul yetişmiyor", "Okulun yazılıları var, YKS'ye vakit kalmıyor."),
 ("Hedefimi değiştirsem mi", "Tıp çok uzak geliyor artık. Bıraksam mı?"),
 ("Konuyu anlamadım", "Türevi üç kere izledim, hâlâ anlamadım."),
 ("Motivasyonum yok", "Hiç içimden gelmiyor. Zorla mı oturayım?"),
 ("Plan çok ağır", "Plan çok dolu hocam, yetişemiyorum."),
 ("Sınav kaygısı", "Denemede ilk 10 dakika hiçbir şey okuyamıyorum."),
 ("Hastalandım", "Grip oldum, 3 gündür masaya oturamadım."),
 ("Kitaplar bitmiyor", "5 kitaba başladım, hiçbiri bitmedi."),
 ("Paragraf yavaş", "Paragrafta süre yetmiyor, hep son 5 soru boş."),
 ("Ezberim uçuyor", "Tarihi çalışıyorum, iki gün sonra hiçbir şey kalmıyor."),
 ("Kardeşim gürültü", "Evde çalışacak sessiz yer yok."),
 ("Dershane mi, evden mi", "Arkadaşlar etüde gidiyor. Ben de gitmeli miyim?"),
 ("Hafta sonu kaçtı", "Hafta sonu hiç çalışmadım, pazartesi utanıyorum."),
 ("Net takıldı", "3 haftadır netim aynı. Artmıyor."),
 ("Kıyaslanmak", "Babam kuzenimle kıyaslıyor."),
 ("Her şeyi bıraktım", "Futbolu bıraktım, yine de yetmiyor."),
 ("Soru çözerken dalıyorum", "Soruya bakıyorum, aklım başka yerde."),
 ("Sabah kalkamıyorum", "Alarmı 5 kere erteliyorum."),
 ("Yanlış yapmaktan korkuyorum", "Emin olmadığım soruyu hiç işaretlemiyorum."),
 ("Bir ders çok geride", "Kimya çok geride kaldı, nereden başlayayım?"),
 ("Yorgunum", "Çok yorgunum ama dinlenince de suçlu hissediyorum."),
 ("Ara tatil bitti", "Ara tatilde planladığımın yarısını yaptım."),
 ("Sosyal medya kıyası", "Herkes 14 saat çalışıyor diye paylaşıyor."),
 ("Deneme sınavı stresi", "Yarın deneme var, şimdiden midem ağrıyor."),
 ("Başaramazsam", "Ya kazanamazsam hocam?"),
 ("Yalnız hissediyorum", "Arkadaşlarımla görüşmüyorum, çok yalnızım."),
 ("Öğretmenim kırdı", "Öğretmen sınıfın önünde ‘sen yapamazsın’ dedi."),
 ("Program bozuldu", "Misafir geldi, bütün günüm gitti."),
 ("Bayram çalışması", "Bayramda çalışmazsam geri kalır mıyım?"),
 ("Son 100 gün paniği", "100 gün kalmış. Hiçbir şey yetişmeyecek."),
 ("Mezun yılı", "Geçen yıl kazanamadım. Bu yıl da olmazsa?"),
 ("İlk kez yükseldim", "Hocam ilk kez 70 netin üstüne çıktım!"),
 ("Yeni başlıyorum", "11. sınıfım, şimdi başlamak erken mi?"),
 ("Tercih kaygısı", "Puanım geldi ama ne yazacağımı bilmiyorum."),
 ("Kaç saat uyumalıyım", "4 saat uyuyup çalışsam daha mı iyi?"),
 ("Soru atlamak", "Takıldığım soruyu bırakamıyorum, 5 dakika uğraşıyorum."),
 ("Aynı hata", "Hep aynı yerde aynı hatayı yapıyorum."),
 ("Kış karanlığı", "Hava erken kararınca hiç çalışasım gelmiyor."),
 ("Bahar yorgunluğu", "Hava ısındı, masaya oturmak işkence."),
 ("Deneme bitmeden sıkılıyorum", "Denemenin ortasında dikkatim dağılıyor."),
 ("Ödül", "Kendime ödül versem şımarık mı olurum?"),
 ("Kıskanmak", "Arkadaşım benden yüksek aldı, sevinemedim."),
 ("Pes etmek üzere", "Bıraksam kimse fark etmez gibi."),
]

# Perşembe — VELİ KÖŞESİ
VELI = [
 ("Kaç soru çözdün diye sormayın", "Her akşam ‘kaç soru?’ diye sormak yerine şunu sorun."),
 ("Deneme sonucu geldiğinde", "Çocuğunuzun deneme sonucu kötü geldi. İlk cümleniz ne olacak?"),
 ("Kıyaslama", "‘Kuzenin yapıyor’ cümlesi hiçbir çocuğa net kazandırmadı."),
 ("Uyku düzeni", "Gece 2'de ışığı yanan çocuğa kızmadan önce bunu okuyun."),
 ("Telefon tartışması", "Telefonu almak mı, birlikte kural koymak mı?"),
 ("Sessiz çalışma alanı", "Çocuğunuzun çalıştığı yerde televizyon sesi geliyor mu?"),
 ("Ev içi yük", "Sınav yılında çocuğa ev işi verilir mi?"),
 ("Karne haftası", "Karneye bakarken önce neye bakmalı?"),
 ("Motivasyon konuşması", "Uzun nasihat değil, tek cümle: ‘Yanındayım.’"),
 ("Dershane kararı", "Dershane, özel ders, koçluk: hangisi ne işe yarar?"),
 ("Sınav kaygısı belirtileri", "Mide ağrısı, uykusuzluk, öfke: kaygı bazen böyle konuşur."),
 ("Ödül ve ceza", "‘Kazanırsan araba’ vaadi neden işe yaramaz?"),
 ("Beslenme", "Sınav yılında sabah kahvaltısı neden önemli?"),
 ("Hafta sonu dengesi", "Pazar günü aile gezmesi sınav yılında yasak mı?"),
 ("LGS velisi", "8. sınıf velisi: LGS yılında en sık yapılan 3 hata."),
 ("Mezun öğrenci", "Mezun yılında evde kalan gencin günü nasıl geçmeli?"),
 ("Öğretmenle iletişim", "Rehber öğretmenle ne zaman görüşmeli?"),
 ("Ekran süresi", "Telefon yasak değil. Saatli."),
 ("Hedef konuşması", "Çocuğunuzun hedefi mi, sizin hedefiniz mi?"),
 ("Kötü gün", "Çocuğunuz ‘bugün hiç çalışmadım’ dedi. Ne diyeceksiniz?"),
 ("Deneme maliyeti", "Her hafta deneme almak şart mı?"),
 ("Ara tatil", "Ara tatilde çocuğa ‘tatil’ yaşatmalı mı?"),
 ("Sınav günü", "Sınav sabahı veliler ne yapmalı, ne yapmamalı?"),
 ("Tercih dönemi", "Tercih listesi: kimin listesi?"),
 ("Kardeşler", "Sınava hazırlanan çocuk ve küçük kardeş: evde denge."),
 ("Övgü", "‘Aferin, zekisin’ yerine ‘aferin, çalıştın’."),
 ("Sessizlik", "Çocuğunuz konuşmuyorsa, sorunu sorularla değil zamanla açın."),
 ("Koçluk nedir", "Koç ders anlatmaz. Peki ne yapar?"),
 ("Haftalık görüşme", "Haftada bir 15 dakika: sadece dinlemek."),
 ("Bayram ziyaretleri", "‘Kaç net yapıyorsun?’ sorusundan çocuğunuzu koruyun."),
 ("Okul mu YKS mi", "Okul notları mı, YKS mi? İkisi rakip değil."),
 ("Harçlık ve bağımsızlık", "Sınav yılında sorumluluk azalmaz, şekil değiştirir."),
 ("Sağlık kontrolü", "Göz ve uyku: çoğu ‘dikkat sorunu’ buradan çıkar."),
 ("Başarısızlık korkusu", "Çocuğunuz kazanamazsa ne olur? Önce siz cevap verin."),
 ("Evde deneme günü", "Cumartesi deneme: ev sessiz, kahvaltı hazır."),
 ("Bütçe", "Pahalı kaynak değil, bitirilen kaynak kazandırır."),
 ("Kıyafet ve sınav", "Sınav günü rahat kıyafet, yanında su ve kimlik."),
 ("Anne–baba ortak dil", "Anne bir şey, baba başka şey diyorsa çocuk kaybolur."),
 ("Sosyal medya", "Çocuğunuzun takip ettiği ‘motivasyon’ hesapları ona iyi gelmiyor olabilir."),
 ("Uzun hafta sonu", "Bayram tatili: 9 günü bölmek."),
 ("11. sınıf velisi", "11. sınıfta başlamak erken değil. Ama sınıf sınıf."),
 ("Sonuç günü", "Sonuç açıklandığında ilk sarılma, sonra puan."),
 ("Kaygılı veli", "Sizin kaygınız çocuğunuza da bulaşıyor olabilir."),
 ("Güven", "Çocuğunuz size yanlış netini söyleyebiliyor mu?"),
 ("Çalışma masası", "İyi bir masa ve iyi bir ışık: en ucuz yatırım."),
 ("Yazılı haftası", "Okul yazılısı ile YKS çakışınca öncelik ne?"),
 ("Mola hakkı", "Mola veren çocuk tembel değil."),
 ("Yıl sonu değerlendirme", "Yılın sonunda puan değil, yol konuşulur."),
]

# Cuma — DOĞRU BİLİNEN YANLIŞLAR (efsane → gerçek)
EFSANE = [
 ("Çok saat = çok net", "‘Günde 12 saat çalışan kazanır.’ Yanlış."),
 ("Deneme her gün çözülür", "‘Her gün deneme çöz.’ Yanlış."),
 ("Müzikle çalışılmaz", "‘Müzikle çalışılmaz.’ Yarı yanlış."),
 ("Gece çalışmak verimli", "‘Gece daha iyi odaklanıyorum.’ Çoğu zaman yanılsama."),
 ("Konu anlatımı izlemek çalışmaktır", "Video izlemek çalışmak değil. İzlediğini çözmek çalışmak."),
 ("Son ay her şeyi değiştirir", "‘Son ay asılırım.’ Son ay tekrar içindir."),
 ("Zeki olan kazanır", "YKS zekâ değil, düzen sınavıdır."),
 ("Kolay konular sona", "Kolay konu sona kalınca kolay puan kaçar."),
 ("Kafein mucizesi", "Enerji içeceği net artırmaz. Uykuyu azaltır."),
 ("Özet çıkarmak şart", "Her konuya özet çıkarmak zaman kaybı olabilir."),
 ("Boş bırakmak kaybettirir", "4 yanlış 1 doğruyu götürür. Yani?"),
 ("11. sınıf erken", "‘Daha 11. sınıftayım.’ En ucuz yıl şimdi."),
 ("Motivasyon beklenir", "Motivasyonu beklersen masaya oturmazsın."),
 ("Tek kaynak yetmez", "Çok kaynak değil, bitmiş kaynak."),
 ("Sabah erken kalkan kazanır", "Erken kalkmak değil, düzenli kalkmak."),
 ("Deneme neti = gerçek net", "Denemedeki net bir fotoğraf, film değil."),
 ("Mezun yılı kolay", "Mezun yılı bol zamanlı ama yalnız bir yıl."),
 ("Ezber her şeydir", "Tarih bile ezber değil, sıralama."),
 ("Koç = öğretmen", "Koç ders anlatmaz. Seni takip eder."),
 ("Yanlış soruya bakılmaz", "Yanlış sorun, bir sonraki doğrun."),
 ("Uyku kaybıdır", "Uyku, ezberin kaydedildiği saattir."),
 ("Sosyal hayat bitmeli", "Arkadaşsız bir yıl, verimli bir yıl değil."),
 ("Paragraf yeteneğe bağlı", "Paragraf yetenek değil, antrenman."),
 ("Matematik kafası", "‘Benim matematik kafam yok.’ Kafası yok, tekrarı yok."),
 ("Bayramda çalışılmaz", "Bayramda çalışmamak geri bırakmaz. Hiç dönmemek bırakır."),
 ("Son hafta yeni konu", "Son hafta yeni konu açmak paniği büyütür."),
 ("Herkes 14 saat çalışıyor", "Sosyal medyadaki masa fotoğrafı gerçek bir gün değil."),
 ("Yazılı notları önemsiz", "OBP puanına eklenir. Önemsiz değil."),
 ("Soru atlamak zayıflık", "Soru atlamak strateji."),
 ("Tekrar sıkıcıdır", "Tekrar sıkıcı değil, kalıcı."),
 ("Dinlenmek suç", "Dinlenen öğrenci tembel değil. Yakıt alıyor."),
 ("Bir kötü deneme her şeyi söyler", "Tek deneme trend değildir."),
 ("Kolay soru herkese kolay", "Kolay soruyu kaçırmak, zor soruyu yapmamaktan pahalı."),
 ("Formül ezberi yeter", "Formül bilmek soruyu çözmek değil."),
 ("TYT kolay, AYT önemli", "TYT neti AYT puanını da taşır."),
 ("Ortalama öğrenci kazanamaz", "Düzenli ortalama, düzensiz zekiyi geçer."),
 ("Kaygı kötüdür", "Biraz kaygı dikkati açar. Fazlası kapatır."),
 ("Son sınıfta her şey biter", "Son sınıf başlangıç değil, devam."),
 ("Tercihte puan her şey", "Tercihte puan kadar şehir, bölüm ve sen varsın."),
 ("Deneme sonrası dinlenmek israf", "Deneme sonrası analiz, deneme kadar önemli."),
 ("Plan esnek olmamalı", "Hiç esnemeyen plan ilk hafta kırılır."),
 ("Sadece çalışınca olur", "Doğru çalışmak, çok çalışmaktan önce gelir."),
 ("Gürültü alışılır", "Gürültüye alışırsın ama dikkatin alışmaz."),
 ("Kitap okumak zaman kaybı", "Paragrafın en iyi antrenmanı kitap."),
 ("Kopya plan işe yarar", "Birincinin planı senin planın değil."),
 ("Hızlı okuma kursu", "Hızlı okumak değil, doğru okumak."),
 ("Soru sayısı yeter", "Kaç soru değil, kaç yanlışın döndüğü."),
 ("Kış tembel yapar", "Kış tembel yapmaz, karanlık yorar. Işığı aç."),
]

# Cumartesi — DENEME GÜNÜ
DENEME = [
 ("Deneme sabahı rutini", "Deneme sabahı: aynı kahvaltı, aynı saat, aynı kalem."),
 ("Soru sırası stratejisi", "Türkçe'den mi başlarsın matematikten mi? Seç ve sabitle."),
 ("İlk tur ikinci tur", "İlk turda emin olduklarını çöz. İkinci turda dön."),
 ("Deneme analizi 20 dakika", "Deneme bitti. En önemli 20 dakika şimdi başlıyor."),
 ("Yanlış defteri", "Her denemeden 5 yanlış deftere. Başka hiçbir şey."),
 ("Boş bırakma kararı", "Boş mu bırakayım, tahmin mi? İki şıkka indiysen işaretle."),
 ("Süre yönetimi", "Matematikte 2 dakikayı geçen soruya işaret koy, geç."),
 ("Net grafiği", "Netlerini bir grafiğe dök. Tek deneme değil, çizgi önemli."),
 ("Optik hatası", "En pahalı yanlış: optiğe kaydırmak."),
 ("Deneme sonrası duygu", "Kötü geçti mi? Bugün analiz yok. Yarın sabah var."),
 ("Evde deneme koşulları", "Evde deneme: telefon başka odada, saat görünür yerde."),
 ("Türkiye geneli deneme", "Türkiye geneli denemede sıralaman neyi söyler?"),
 ("Branş denemesi", "Hafta içi branş denemesi, hafta sonu genel."),
 ("Dikkat dağılınca", "Denemenin ortasında dağıldın mı? 30 saniye gözünü kapat."),
 ("Kolay soruyu kaçırmak", "Bu denemede kaç kolay soruyu kaçırdın? En kolay net orada."),
 ("Deneme sıklığı", "Eylülde haftada 1, mayısta haftada 2."),
 ("AYT denemesi", "AYT denemesi TYT'den uzun. Enerji planı yap."),
 ("Deneme karşılaştırma", "Kendinle karşılaştır. Arkadaşınla değil."),
 ("Konu eksiği mi, dikkat mi", "Yanlışını ikiye ayır: bilmediğim, dikkatsizlik."),
 ("Deneme sonrası ödül", "Deneme bitince 1 saat tamamen boş. Hak ettin."),
 ("Zor deneme", "Deneme zordu. Herkes için zordu."),
 ("Paragraf süresi", "Denemede paragrafa kaç dakika ayırdın? Ölç."),
 ("Deneme sonucu paylaşmak", "Netini herkese söylemek zorunda değilsin."),
 ("Sınav provası", "Bu cumartesi gerçek sınav saatinde başla: 10.15."),
 ("Yorgun deneme", "Yorgunken çözülen deneme, yorgunluğu ölçer."),
 ("Kalem ve silgi", "Sınav günü hangi kalemi kullanacağını bugünden seç."),
 ("Soru atlama cesareti", "Bu denemede 3 soru bilerek atla. Süre ne oldu, bak."),
 ("Denemeden plan çıkar", "Denemedeki 3 eksik, pazartesinin planı."),
 ("Deneme korkusu", "Deneme sınav değil, antrenman."),
 ("Net düşüşü", "Net düştü mü? Deneme zorlaştı mı, sen mi yoruldun?"),
 ("Fen sırası", "Fende fizik mi önce kimya mı? Kendi sıranı bul."),
 ("Deneme arası mola", "TYT'den sonra AYT'ye geçerken ne yiyeceksin?"),
 ("Dönem sonu denemesi", "Dönem bitti. Bu deneme dönemin karnesi."),
 ("Net hedefi gerçekçi", "Bir sonraki deneme hedefi: +2 net. +20 değil."),
 ("Bayram denemesi", "Uzun tatilin bir gününü deneme günü yap."),
 ("Son denemeler", "Son 3 deneme: yeni bir şey deneme."),
 ("Deneme stresi bedende", "Deneme öncesi karın ağrısı normal. Nefes 4-4-4."),
 ("Kodlama zamanı", "Optiği sonda mı dolduruyorsun? Her 10 soruda bir doldur."),
 ("Kontrol turu", "Son 5 dakika: sadece boş bıraktıklarına bak."),
 ("Deneme notları", "Denemeden sonra 3 cümle yaz: ne iyi, ne kötü, ne değişecek."),
 ("Deneme bağımlılığı", "Çok deneme çözüp analiz etmemek, hiç çözmemek gibi."),
 ("Kolaydan zora", "Kolay soruları topla, zoru sona bırak."),
 ("Deneme yorgunluğu", "Deneme sonrası baş ağrısı: su içtin mi?"),
 ("Tahmin stratejisi", "Hiç fikrin yoksa boş bırak. İki şıkka indiysen işaretle."),
 ("Yaz denemesi", "Yazın ayda 2 deneme: formu korur."),
 ("İlk deneme", "İlk deneme bir harita. Not değil."),
 ("Deneme sonrası uyku", "Deneme günü erken yat. Beyin yorgun."),
 ("Sıralama kaygısı", "Sıralaman değişir. Netin değişince."),
]

# Pazar — PAZAR AKŞAMI (duygu, moral, haftayı kapatma)
PAZAR = [
 ("Pazar akşamı ağırlığı", "Pazar akşamı içinde bir ağırlık mı var? Yalnız değilsin."),
 ("Haftayı kapat", "Bu haftanın tek iyi şeyini yaz. Bir tane yeter."),
 ("Kendine koç ol", "Kendine bir arkadaşına konuşur gibi konuş."),
 ("Yetmiyorum hissi", "‘Yetmiyorum’ bir his. Gerçek değil."),
 ("Yarın yeni hafta", "Yarın sıfırdan değil, kaldığın yerden."),
 ("Kaygıyla yaşamak", "Kaygı gitmeyecek. Seninle birlikte çalışacak."),
 ("Küçük zaferler", "Bu hafta bir soruyu ilk kez yaptın mı? Bu bir zafer."),
 ("Mükemmel hafta yok", "Mükemmel hafta yok. İyi yeter."),
 ("Dinlenme hakkı", "Bugün dinlendiysen, suçluluk duymana gerek yok."),
 ("Kıyas bırak", "Bu hafta kimseye bakma. Sadece dünkü sene."),
 ("Neden başladın", "Neden başladığını hatırla. Kâğıda yaz."),
 ("Yalnızlık", "Bu yol yalnız hissettirir. Ama yalnız değilsin."),
 ("Beden de çalışır", "Bu hafta kaç kere yürüdün? Beyin bacaklarla da çalışır."),
 ("Sınav senin değerin değil", "Bir sınav, senin değerini ölçmez."),
 ("Gelecek kaygısı", "Gelecek büyük. Yarın küçük. Yarına bak."),
 ("Ailene teşekkür", "Bu hafta evde sana destek olan birine teşekkür et."),
 ("Uyku borcu", "Bu gece erken yat. Pazartesi seni teşekkürle karşılar."),
 ("Kötü hafta", "Kötü hafta oldu. Kötü yıl olmayacak."),
 ("Hedefi küçült", "Hedef büyük olabilir. Adım küçük olmalı."),
 ("Telefonsuz akşam", "Bu akşam bir saat telefonsuz. Sadece bir saat."),
 ("İyi ki çalıştın", "Yorgunsan, çalıştığın içindir."),
 ("Pes etmek istemek", "Bırakmak istemek normal. Bırakmamak da seçim."),
 ("Yavaş ilerleme", "Yavaş ilerlemek, durmaktan iyidir."),
 ("Kendini affet", "Bu hafta yapmadıkların için kendini affet. Yarın var."),
 ("Plan hazırlığı", "Yarının ilk işini bu akşam belirle."),
 ("Mevsim değişimi", "Hava değişti, ruh halin de değişebilir. Normal."),
 ("Işık ve ruh hali", "Kış akşamları erken karanlık. Masaya iyi bir lamba koy."),
 ("Bahar huzursuzluğu", "Hava güzelleşince dışarısı çağırır. 1 saat git, dön."),
 ("Sınav yaklaşırken", "Sınav yaklaştıkça zaman hızlanır gibi olur. Aynı hızda."),
 ("Gurur", "Kendinle gurur duyduğun bir şey söyle."),
 ("Karşılaştırma tuzağı", "Sosyal medyadaki masa, gerçek hayat değil."),
 ("Sabır", "Net artışı merdiven değil, rampa. Önce düz gider."),
 ("Anlam", "Bu yıl sadece puan değil, disiplin kazandırıyor."),
 ("Arkadaşlık", "Bu hafta bir arkadaşını ara. Ders konuşmadan."),
 ("Hayır demek", "Bu hafta ‘hayır’ dediğin şey, ‘evet’ dediğin hedefi korudu."),
 ("Duygu günlüğü", "Bugün nasıl hissettin? Bir kelimeyle."),
 ("Hafta puanı", "Haftana 10 üzerinden kaç verirsin? 6 iyi bir not."),
 ("Kendi hızın", "Herkesin saati farklı. Senin saatin de işliyor."),
 ("Bedenin sinyali", "Başın ağrıyorsa, gözün yorgunsa: dur."),
 ("Umut", "Umut plan değildir. Ama plansız umut da olmaz."),
 ("Dua, niyet, dilek", "Bu hafta için tek bir dileğin ne?"),
 ("Sessiz akşam", "Bu akşam sadece dinlen. Yarın başlarız."),
 ("Kaybettiğin günler", "Kaybettiğin gün yok. Ders çıkardığın gün var."),
 ("Kendine mektup", "Haziranda okuyacağın bir cümle yaz."),
 ("Yeni başlangıç", "Her pazartesi yeni başlangıç değil. Devam."),
 ("Kontrol edebildiklerin", "Soru zorluğunu değil, bugünü kontrol edebilirsin."),
 ("Aileyle akşam", "Bu akşam ailenle yemek. Konu YKS olmasın."),
 ("Son pazar", "Sınavdan önceki son pazar gibi düşün: sakin."),
]

# Mevsime bağlı konular: başlık -> hangi aylarda yayınlanabilir.
# Buradaki konular yalnız bu aylarda seçilir; diğerleri yıl boyu sırayla gelir.
MEVSIM = {
 # Plan
 "Kış saatleri": {11, 12, 1}, "Yaz planı": {7, 8}, "Okul yoğun haftası": {10, 11, 12, 3, 4, 5},
 "Sınavdan geriye plan": {3, 4, 5}, "Tatil sonrası dönüş": {11, 2, 3},
 # Aynı Hafta
 "Kış karanlığı": {11, 12, 1}, "Bahar yorgunluğu": {4, 5}, "Son 100 gün paniği": {3},
 "Tercih kaygısı": {7, 8}, "Yeni başlıyorum": {6, 7, 8, 9}, "Mezun yılı": {9, 10, 7, 8},
 "Ara tatil bitti": {11, 3}, "Bayram çalışması": {3, 5}, "Hastalandım": {12, 1, 2},
 "Okul yetişmiyor": {10, 11, 12, 3, 4, 5},
 # Veli
 "Karne haftası": {1, 6}, "Tercih dönemi": {7, 8}, "Sınav günü": {6}, "Bayram ziyaretleri": {3, 5},
 "Uzun hafta sonu": {5}, "11. sınıf velisi": {6, 7, 8, 9}, "Sonuç günü": {7},
 "Yıl sonu değerlendirme": {6, 7}, "Ara tatil": {11, 3}, "Yazılı haftası": {10, 11, 12, 3, 4, 5},
 "Mezun öğrenci": {9, 10, 7, 8}, "LGS velisi": {9, 10, 11},
 # Efsane
 "Kış tembel yapar": {11, 12, 1}, "Son ay her şeyi değiştirir": {4, 5}, "Son hafta yeni konu": {5, 6},
 "Bayramda çalışılmaz": {3, 5}, "Tercihte puan her şey": {7, 8}, "11. sınıf erken": {6, 7, 8, 9},
 "Son sınıfta her şey biter": {9, 10}, "Mezun yılı kolay": {7, 8, 9},
 # Deneme
 "Son denemeler": {5, 6}, "Bayram denemesi": {3, 5}, "Yaz denemesi": {6, 7, 8}, "İlk deneme": {9, 10},
 "Dönem sonu denemesi": {1}, "Sınav provası": {4, 5, 6},
 # Pazar
 "Işık ve ruh hali": {11, 12, 1}, "Bahar huzursuzluğu": {4, 5}, "Sınav yaklaşırken": {4, 5, 6},
 "Son pazar": {6}, "Mevsim değişimi": {10, 3},
}
