"""Videoların gövdesi: konu başlığı -> 3 kısa satır (her biri ~3 sn ekranda).
Başlığa bağlı tutulur, tarihe değil: takvim kayarsa gövde konusuyla gider.
'Aynı Hafta' serisinde satırlar sırayla koç / öğrenci / koç mesajıdır.
Gövdesi yazılmamış gün üretilmez; iş akışı uyarı verip atlar."""

GOVDE = {
 # Özel günler
 "Dünya Ruh Sağlığı Günü": ["Kalp çarpıntısı, uykusuzluk, mide ağrısı: kaygı böyle konuşur.", "Güvendiğin bir yetişkine anlatmak ilk adım.", "Uzun sürüyorsa okul rehber öğretmeni ya da bir uzman."],
 "İlk deneme bir harita": ["Netin düşük çıkabilir. Olması gereken bu.", "Hangi derste kaç boş var? Haritan o.", "Bir sonraki denemeye tek hedef: +2 net."],
 # Pazar Akşamı
 "Pazar akşamı ağırlığı": ["Pazar akşamı herkesin göğsüne biraz ağırlık çöker.", "Yarının ilk işini şimdi yaz. Sadece ilkini.", "Sonra telefonu bırak, erken uyu."],
 "Haftayı kapat": ["Bu haftanın tek iyi şeyini yaz.", "Bir soruyu ilk kez yapmak da sayılır.", "Kötüleri değil, iyi olanı hatırla. Yarın ona eklersin."],
 "Mevsim değişimi": ["Hava değişince uyku ve enerji de değişir.", "Birkaç gün yavaş hissetmen normal.", "Planı küçült, ritmi koru. Bir haftada alışırsın."],
 "Kendine koç ol": ["Kötü bir günde kendine ne diyorsun?", "Aynı şeyi bir arkadaşına söyler miydin?", "Kendinle de onunla konuştuğun gibi konuş."],
 # Haftanın Planı
 "Haftayı üç işle başlat": ["Pazartesi 20 iş yazınca cuma 5'i biter.", "Bu hafta sadece 3 iş seç. Hepsine gün ve saat ver.", "Üçü de biterse, dördüncüyü o zaman ekle."],
 "Plan kâğıtta değil, takvimde": ["‘Matematik çalışacağım’ bir niyet.", "‘Salı 19:00, 40 problem’ bir plan.", "Her işe gün ve saat ver. Plan o zaman çalışır."],
 "Okul yoğun haftası": ["Yazılı haftası geldi. Önce yazılılar.", "YKS için her gün sadece 30 dakika: paragraf ve problem.", "Yazılılar bitince tam plana dön. Hiçbir şey kaybolmadı."],
 "Pazartesi sendromu": ["Pazartesi ağır geliyorsa, pazar akşamı plan yoktur.", "Pazar akşamı 10 dakika: haftanın 3 işi.", "Pazartesi sabahı düşünmezsin, başlarsın."],
 # Ders Taktiği
 "Paragrafta önce soru kökü": ["Önce soru kökünü oku: ne soruluyor?", "Sonra paragrafı o gözle oku.", "Aradığını bilerek okuyan daha hızlı bulur."],
 "Problemlerde tabloyu çiz": ["Kişiler satıra, zamanlar sütuna.", "Bugün, x yıl önce, y yıl sonra: üç sütun.", "Tablo dolunca denklem kendini yazar."],
 "Açıyı çizime yaz": ["Soruda verilen her açıyı şeklin üstüne yaz.", "Sonra üçgenlerin iç açılarını tamamla.", "Çoğu zaman aradığın açı kendiliğinden çıkar."],
 "Birimle kontrol et": ["Cevabın birimi ne olmalı? Önce onu yaz.", "Hız m/s ise, işlemin sonunda m/s çıkmalı.", "Birim tutmuyorsa formülü yanlış kurmuşsundur."],
 # Aynı Hafta (koç / öğrenci / koç)
 "Mezun yılı": ["Geçen yıl nerede takıldın, biliyor musun?", "Deneme stresi ve düzensizlik sanırım.", "O zaman bu yılın planı ikisine göre. Aynı yıl değil bu."],
 "Yeni başlıyorum": ["Erken değil. En rahat yıl şu an.", "Ne kadar çalışayım peki?", "Günde 1 saat yeter. Ama her gün. Önce TYT temeli."],
 "Okul yetişmiyor": ["Yazılı haftası YKS'yi durdurmaz, küçültür.", "Her gün ne kadar?", "30 dakika paragraf ve problem. Yazılılar bitince tam plan."],
 "Dün hiç çalışmadım": ["Hayır. İki katı yaparsan yarın da yorgun olursun.", "Peki ne yapayım?", "Bugünün planı ne ise o. Dün geçti, bugün sayılır."],
 # Veli Köşesi
 "LGS velisi": ["1. Her denemeden sonra sonuç sorgusu.", "2. Kardeşle, kuzenle kıyaslamak.", "3. Hafta sonunu tamamen derse ayırmak."],
 "Mezun öğrenci": ["Mezun yılında en büyük risk yalnızlık ve düzensizlik.", "Sabah kalkış saati sabit olsun, gün bir yapıya otursun.", "Haftada bir gün dışarı çıkmak ceza değil, bakım."],
 "Yazılı haftası": ["Yazılı haftasında önce okul.", "YKS'ye her gün kısa bir parça: 30 dakika.", "Yazılı notları OBP'ye girer. İkisi rakip değil."],
 "Kaç soru çözdün diye sormayın": ["‘Kaç soru?’ sorusu bir sınav gibi gelir.", "Onun yerine: ‘Bugün en zor ne vardı?’", "Cevap sorun anlatır. Soru sayısı anlatmaz."],
 # Doğru Bilinen Yanlışlar (gerçek)
 "11. sınıf erken": ["11. sınıf, konuları acele etmeden oturtacağın yıl.", "Günde 1 saat TYT temeli, 12. sınıfta sana aylar kazandırır.", "Erken başlayan yavaş gidebilir. Geç başlayan koşmak zorunda."],
 "Son sınıfta her şey biter": ["Son sınıf sıfırdan başlama yılı değil.", "11. sınıfta ne attıysan onun üstüne kurarsın.", "Hiçbir şey atmadıysan da geç değil: plan küçük, düzen sıkı."],
 "Çok saat = çok net": ["12 saat masada oturmak, 12 saat çalışmak değil.", "Odaklı 5 saat, dağınık 12 saati geçer.", "Saat değil, çözülen ve dönülen soru sayılır."],
 "Deneme her gün çözülür": ["Her gün deneme çözen analize vakit bulamaz.", "Eylül–mart haftada 1, nisandan sonra 2.", "Deneme ölçer. Asıl artış analizden gelir."],
 # Deneme Günü
 "İlk deneme": ["İlk denemenin neti seni tanımlamaz.", "Boş bıraktıkların konu eksiğin, yanlışların dikkat eksiğin.", "İkisini ayrı listele. Pazartesinin planı hazır."],
 "Deneme sabahı rutini": ["Deneme sabahı yeni bir şey deneme.", "Her zamanki kahvaltı, su, aynı kalem.", "Sınav sabahı da böyle olacak. Şimdiden alış."],
}

# ── 17 Ekim – 31 Aralık 2026 ─────────────────────────────────────
GOVDE.update({
 # Ekim
 "Soru sırası stratejisi": ["Her denemede başka sırayla başlamak, her seferinde yeniden alışmak demek.", "Bir sıra seç: Türkçe, sosyal, matematik, fen gibi.", "Beş deneme aynı sırayla git. Sonra karar ver."],
 "Yetmiyorum hissi": ["‘Yetmiyorum’ bir düşünce. Ölçüm değil.", "Ölçüm şu: geçen ay kaç net, bu ay kaç net?", "Çizgi yukarı gidiyorsa, yetiyorsun."],
 "En zor dersi sabaha koy": ["Günün ilk saatinde irade en taze.", "En çok ertelediğin dersi o saate yaz.", "Kolay dersleri akşama bırak. Yorgunken de yapılır."],
 "Mol köprüsü": ["Gram mı verdi? Mole çevir.", "Tanecik mi, hacim mi soruyor? Molden ona geç.", "Her soruda aynı köprü: veri → mol → sorulan."],
 "Denemede düştüm": ["Hayır. Deneme zorlaştı mı, sen mi yoruldun, önce ona bakalım.", "Deneme zordu ama ben de dağınıktım.", "O zaman bu hafta 3 dikkat hatanı yazalım. Net geri gelir."],
 "Deneme sonucu geldiğinde": ["İlk cümle puan olmasın.", "‘Nasıl geçti, sen nasılsın?’ yeter.", "Analiz ertesi gün, çocuk hazır olduğunda."],
 "Müzikle çalışılmaz": ["Sözlü müzik paragrafta dikkati böler.", "Sözsüz, tanıdık müzik tekrar ve soru çözümünde sorun olmayabilir.", "Deneme günü müziksiz: sınavda da müzik yok."],
 "İlk tur ikinci tur": ["İlk tur: bildiğin, hızlı gördüğün sorular.", "Takıldığın soruya işaret koy, geç.", "İkinci turda kalan süreyi işaretlilere harca."],
 "Yarın yeni hafta": ["Geçen hafta ne olduysa oldu.", "Yarın kaldığın konudan, kaldığın sayfadan devam.", "Sıfırdan başlamak her hafta yorar. Devam etmek yormaz."],
 "25 dakikalık blok": ["25 dakika çalış, 5 dakika kalk.", "Dört blok bitince 20 dakika uzun mola.", "Saat ölçme, blok say: bugün kaç blok?"],
 "Şemayla çalış": ["Bir sayfa okumak yerine bir şema çiz.", "Mitozu çiz, sonra kitabı kapatıp yeniden çiz.", "Çizemediğin yer, bilmediğin yerdir."],
 "Arkadaşım benden iyi": ["Onun kaç saat çalıştığını gerçekten biliyor musun?", "Bilmiyorum, öyle anlatıyor.", "O zaman kendi grafiğine bak. Kıyas, tek kişiyle: geçen ayki sen."],
 "Cumhuriyet Bayramı": ["Bugün ders değil, bayram.", "Bu ülkenin okullarında okuyabilmek de onun eseri.", "Yarın kaldığın yerden devam."],
 "Gece çalışmak verimli": ["Gece sessiz olduğu için verimli gelir.", "Ama uyku bölünürse ertesi gün iki saat kaybedersin.", "Sınav sabah 10.15'te. Beynini sabaha alıştır."],
 "Deneme analizi 20 dakika": ["Yanlışları ikiye ayır: bilmedim, dikkat etmedim.", "Bilmediklerin konu listesi, dikkat hataların alışkanlık listesi.", "Her listeden en çok tekrar eden 3 tane: haftanın planı."],
 # Kasım
 "Işık ve ruh hali": ["Hava erken kararınca beden uykuya hazırlanır.", "Masaya sıcak ve güçlü bir lamba koy.", "Gündüz 20 dakika dışarı çık. Işık da çalışmanın parçası."],
 "Tatil sonrası dönüş": ["Tatil dönüşü ilk hafta tam hız yorar.", "Planın yarısıyla başla, çarşamba tam plana geç.", "Önce ritim, sonra yük."],
 "Zaman çizelgesi": ["Kâğıda bir çizgi çiz: yüzyıllar.", "Her olayı çizgide yerine koy.", "Soru ‘önce hangisi’ derse, çizgi cevabı verir."],
 "Ara tatil bitti": ["Yarısı iyi bir oran. Hiç yapmamaktan iyi.", "Ama kötü hissediyorum.", "Hangi yarıyı yaptığına bak. Kalanı önümüzdeki iki haftaya dağıtalım."],
 "Ara tatil": ["İlk 2–3 gün gerçek tatil olsun.", "Sonra her gün birkaç saatlik düzenli tekrar.", "Tatil bitince çocuk yorgun değil, hazır dönsün."],
 "Kış tembel yapar": ["Kışın yorgunluk karanlıktan gelir.", "Işıklı oda, gün içinde dışarıda 20 dakika.", "Yorgunluk tembellik değil. Ona göre plan kurulur."],
 "Yanlış defteri": ["Her denemeden sadece 5 yanlış seç.", "Soruyu yapıştır, doğru çözümü kendi cümlenle yaz.", "Cuma akşamı defteri baştan oku. Hepsi bu."],
 "Kaygıyla yaşamak": ["Sınav yaklaştıkça kaygı gelecek.", "Onu kovmaya çalışma, adını koy: ‘şu an kaygılıyım.’", "Sonra küçük bir iş yap. İş kaygıyı küçültür."],
 "Kış saatleri": ["Hava artık 17:45'te kararıyor.", "Okuldan dönünce ilk iş, ışık varken en zor ders.", "Karanlık saatlere tekrar ve kolay soru."],
 "10 Kasım": ["Saat 09:05.", "Bir dakikalık saygı duruşu.", "Gençliğe emanet ettiği yolda, çalışarak."],
 "Kış karanlığı": ["Çok normal. Karanlık bedeni yavaşlatır.", "Ne yapayım o zaman?", "Işık varken zor ders, karanlıkta tekrar. Odanı aydınlat."],
 "Kıyaslama": ["Kıyas bir çocuğa ‘yetmiyorsun’ diye duyulur.", "Onun yerine geçen aya göre konuşun.", "‘Geçen ay 42, şimdi 46. Nasıl yaptın?’"],
 "Ara tatil planı": ["İlk 3 gün dinlen: uyku, arkadaş, hareket.", "Sonraki 6 gün: her gün 4 blok tekrar ve bir deneme.", "Tatilin sonunda eksik listesi kısalmış olsun."],
 "Boş bırakma kararı": ["Hiç fikrin yoksa boş bırak.", "İki şıkka indiysen işaretle.", "4 yanlış 1 doğruyu götürür. Kör tahmin ortalamada kazandırmaz."],
 "Küçük zaferler": ["Büyük hedef uzakta, küçük zaferler bu hafta.", "İlk kez yaptığın bir soru, erken kalktığın bir sabah.", "Bunları bir yere yaz. Kötü günde okursun."],
 "Boş gün planla": ["Hiç boş gün yoksa, beden bir gün kendisi alır.", "Haftada bir gün tamamen boş olsun.", "Boş gün suçluluk değil, planın parçası."],
 "Harita üstünde çalış": ["Coğrafya sorusu bir yer sorar.", "Konuyu okurken haritada göster: nerede, neden orada?", "Harita aklında kalır, cümle kalmaz."],
 "Uyuyamıyorum": ["Yatmadan önce son bir saat telefon var mı?", "Evet, biraz bakıyorum.", "Bir hafta telefonu 23:00'te başka odaya koy. Sonra konuşalım."],
 "Uyku düzeni": ["Gece uyuyamamak çoğu zaman kaygının işaretidir.", "Kızmak yerine birlikte bir saat belirleyin: telefon 23:00'te salonda.", "Sabah aynı saatte kalkış, akşamı da düzeltir."],
 "Konu anlatımı izlemek çalışmaktır": ["Video izlerken her şey anlaşılır gelir.", "Ama sınav izlediğini değil, çözdüğünü sorar.", "Her 20 dakikalık videodan sonra 20 soru."],
 "Süre yönetimi": ["Bir soruya 2 dakikadan fazla takıldıysan işaretle.", "Geç, sona dön.", "Tek soru için 5 dakika, 3 kolay soruyu götürür."],
 "Mükemmel hafta yok": ["Planın hepsi bitmedi mi?", "Yüzde 70 bittiyse iyi bir haftaydı.", "Mükemmel değil, sürekli olan kazanır."],
 "Plan bozulursa ne olur": ["Misafir gelir, hasta olursun, plan bozulur.", "Bozulan günü telafi etmeye çalışma.", "Ertesi gün planın neresindeysen oradan devam et."],
 "Öğretmenler Günü": ["Hepimizin hayatında bir öğretmen var.", "Bir cümlesiyle yön değiştirdiğimiz.", "Bugün ona bir mesaj at. Öğretmenler Günü kutlu olsun."],
 "Matematik korkusu": ["Korku genelde temel eksikten gelir.", "Evet, bazı konular hiç oturmadı.", "O zaman bu hafta en temelden: sayılar ve işlem. Kolay sorudan başlayacağız."],
 "Telefon tartışması": ["Telefonu almak kavga başlatır.", "Birlikte kural koymak işe yarar: ders saatinde başka odada.", "Kuralı siz de uygularsanız daha çok işe yarar."],
 "Zeki olan kazanır": ["Zekâ işe yarar ama tek başına yetmez.", "YKS dokuz ay düzen ister.", "Her gün aynı saatte masaya oturan, zeki ama düzensizi geçer."],
 "Net grafiği": ["Her denemenin netini bir çizgiye yaz.", "Tek düşüş bir şey söylemez.", "Üç denemelik yön söyler: yukarı mı, düz mü?"],
 "Dinlenme hakkı": ["Bugün dinlendin mi? Güzel.", "Dinlenen beyin yarın daha iyi çalışır.", "Suçluluk duyma. Bu da planın parçası."],
 "Soru sayısı mı, saat mi?": ["‘5 saat çalıştım’ ne yaptığını söylemez.", "‘120 soru, 14 yanlış’ söyler.", "Günün sonunda sayıyı yaz. İlerlemeyi sayı gösterir."],
 # Aralık
 "YKS'ye 200 gün": ["200 gün uzun gibi görünür, çabuk geçer.", "Haftada 6 iyi gün, 1 dinlenme.", "Her hafta bir deneme, her deneme bir analiz."],
 "Hastalandım": ["Önce iyileş. Hasta çalışmak iki kat kaybettirir.", "Ama geri kalıyorum.", "İyileşince ilk 2 gün yarım plan. Kaçanı dağıtırız, yığmayız."],
 "Sessiz çalışma alanı": ["Televizyon sesi dikkati sessizce yer.", "Çalışma saatinde evin bir köşesi sessiz olsun.", "Bu bir kural değil, destek."],
 "Kolay konular sona": ["Kolay konular ‘nasılsa yaparım’ diye sona kalır.", "Sonra zaman yetmez, kolay puan kaçar.", "Kolay konuyu erken bitir, cebe koy."],
 "Optik hatası": ["Bir soruyu atladın, sonraki bütün cevaplar bir satır kaydı.", "Her 10 soruda bir optiği kontrol et.", "Deneme bitmeden son 5 dakikayı optiğe ayır."],
 "Kıyas bırak": ["Bu hafta kimsenin netine bakma.", "Sadece kendi dünkü sayına bak.", "Dünden biraz iyiysen, doğru yoldasın."],
 "Okul sonrası ilk saat": ["Okuldan gelince hemen masaya oturmak zor.", "İlk saat: yemek ve 20 dakika hiçbir şey.", "Sonra masaya. Dinlenmiş beyin daha hızlı başlar."],
 "Yeni nesil soru okuma": ["Uzun metin seni korkutmasın.", "Önce soru cümlesini oku, sorulanın altını çiz.", "Sonra metinde sadece gerekli sayıları topla."],
 "Telefonu bırakamıyorum": ["Telefon masadaysa sen de telefondasın.", "Başka odaya koyunca aklım orada kalıyor.", "İlk 3 gün öyle olur. Dördüncü gün unutursun. Deneyelim."],
 "Ev içi yük": ["Küçük bir sorumluluk çocuğa iyi gelir.", "Masayı kurmak, çöpü atmak: 10 dakika.", "Büyük yükler sınav yılında azalsın, sıfırlanmasın."],
 "Kafein mucizesi": ["Enerji içeceği bir saat uyanık tutar.", "Sonra gece uykunu bozar.", "Uyku bozulunca ertesi gün net düşer."],
 "Deneme sonrası duygu": ["Kötü geçen denemenin ardından hemen analiz yapma.", "Bugün yürü, ye, erken uyu.", "Yarın sabah sakin kafayla yanlışlara bak."],
 "Neden başladın": ["Yorulduğun gün hedef uzak görünür.", "Neden başladığını bir kâğıda yaz.", "Masanın önüne as. Zor günde oku."],
 "Tekrar günü": ["Her hafta yeni konu eklemek, eskiyi unutturur.", "Bu hafta geçen haftanın konularını tekrar et.", "Tekrar edilen konu, sınavda hatırlanır."],
 "Dil bilgisinde eleme": ["Emin olamadığın soruda doğru şıkkı arama.", "Kesin yanlış olanları tek tek ele.", "İki şık kalırsa kurala dön, karar ver."],
 "Ailem baskı yapıyor": ["Annen de kaygılı. Soru sayısı ona güven veriyor.", "Ama her akşam hesap veriyor gibiyim.", "Haftada bir gün sen anlat: ne yaptın, ne zorladı. Soru azalır."],
 "Motivasyon konuşması": ["Uzun nasihat dinlenmez.", "Tek cümle akılda kalır: ‘Yanındayım.’", "Sonrası sessizlik. Çocuk isterse konuşur."],
 "Özet çıkarmak şart": ["Güzel özet yazmak saatler alır.", "Çoğu zaman o saatlerde soru çözülebilirdi.", "Sadece ezber gereken konulara kısa not, gerisine soru."],
 "Evde deneme koşulları": ["Evde deneme, sınavın provasıdır.", "Telefon başka odada, saat görünür yerde, sınav saatinde başla.", "Masada su ve iki kalem. Başka hiçbir şey."],
 "Yalnızlık": ["Bu yıl arkadaşlarla daha az görüşüyorsun.", "Yalnız hissetmek normal.", "Haftada bir kez birini ara ya da buluş. Ders konuşmadan."],
 "Yılın en uzun gecesi": ["Bugün en kısa gün, en uzun gece.", "Yarından itibaren her gün biraz daha ışık.", "En karanlık yeri geçtin."],
 "Sayı basamakları": ["ab iki basamaklı sayı ise 10a + b.", "Harfleri hemen bu şekle çevir.", "Gerisi basit bir denklem."],
 "Hedefimi değiştirsem mi": ["Şu an netin kaç, hedefin için kaç lazım?", "Arada 30 net var.", "Altı ayda 30 net zor ama olur. Karar mart denemelerinden sonra."],
 "Dershane kararı": ["Dershane konu anlatır ve deneme yaptırır.", "Özel ders tek bir eksiği kapatır.", "Koç planı kurar ve takip eder. İhtiyaca göre seçilir."],
 "Boş bırakmak kaybettirir": ["4 yanlış 1 doğruyu götürür.", "Kör tahmin ortalamada ne kazandırır ne kaybettirir.", "İki şıkka indiysen işaretle; hiç fikrin yoksa boş bırak."],
 "Türkiye geneli deneme": ["Türkiye geneli deneme sıralaman bir fotoğraf.", "Katılanlar ve zorluk her seferinde değişir.", "Asıl bakacağın: kendi netinin yönü."],
 "Beden de çalışır": ["Masada 6 saat oturan beden yorulur.", "Günde 20 dakika yürüyüş dikkati açar.", "Hareket de çalışmanın parçası."],
 "Telefon başka odada": ["Telefon masadaysa bildirim beklersin.", "Başka odaya koy, sessize al.", "Mola saatinde bakarsın. Mola daha tatlı olur."],
 "Türevde grafik oku": ["Grafik verildiğinde önce türevin işaretine bak.", "Türev pozitifse artan, negatifse azalan.", "İşaret değiştiği yer ekstremum."],
 "Konuyu anlamadım": ["Üç kere izlemek yerine bir kere çöz.", "Hangi adımda takılıyorsun?", "O adımın 5 kolay sorusunu çözelim. Anlamak çözerken gelir."],
 "Yılbaşı gecesi": ["Bu gece ders yok.", "Aileyle, arkadaşlarla, dinlenerek.", "Yarın 2027. Sınav yılı sakin başlasın."],
})

# ── 1 Ocak – 31 Mart 2027 ────────────────────────────────────────
GOVDE.update({
 # Ocak: karne, yarıyıl
 "2027: sınav yılı": ["Yeni yıl kararı genelde ocak ortasında biter.", "Yeni plan yapma. Eylülden beri işleyen planı sakinleştir.", "Tek değişiklik: her hafta bir deneme, bir analiz."],
 "Dönem sonu denemesi": ["Bu deneme, dönemin karnesi.", "Eylüldeki ilk denemenle yan yana koy.", "Hangi derste en çok yol aldın? Oradan güç al."],
 "Sınav senin değerin değil": ["Bir sınavdaki netin bir günü ölçer.", "Senin emeğini, sabrını, iyiliğini ölçmez.", "Sonuç ne olursa olsun, sen o sonuçtan büyüksün."],
 "Haftalık tek hedef": ["Bu hafta her şeyi düzeltmeye çalışma.", "Tek cümle yaz: ‘Bu hafta paragrafta süreyi 2 dakika kısaltacağım.’", "Pazar akşamı bu cümleye bak."],
 "Dönem–sanatçı eşleşmesi": ["Bir tablo çiz: dönem, sanatçı, eser, özellik.", "Her gün beş satır ekle.", "Soru ‘hangisi bu döneme ait değil’ derse, tablo cevap verir."],
 "Motivasyonum yok": ["Motivasyonu bekleme. Masaya otur, 10 kolay soru çöz.", "10 soruda ne değişir?", "Başlamak motivasyon getirir. Beklemek getirmez."],
 "Karne haftası": ["Önce çocuğunuzun yüzüne bakın, sonra nota.", "Hangi derste yükseldi? Oradan başlayın.", "Düşük notu yarıyılda birlikte ele alırsınız, bu akşam değil."],
 "Motivasyon beklenir": ["Motivasyon bir duygu, gelir gider.", "Düzen bir karar, her gün aynı saatte masaya oturmak.", "Düzenli olanın motivasyonu çalışırken gelir."],
 "Branş denemesi": ["Genel deneme her şeyi ölçer, yorar.", "Hafta içi sadece bir ders: 20 dakikalık branş denemesi.", "Hafta sonu genel deneme. Denge bu."],
 "Gelecek kaygısı": ["Haziranı, üniversiteyi, meslek seçimini düşünmek ağır gelir.", "Onları şimdi çözmek zorunda değilsin.", "Bugünün işini bitir. Gelecek bugünlerden yapılır."],
 "Zayıf konu listesi": ["‘Matematik kötü’ bir liste değil.", "‘Üslü sayılar, problemler, olasılık’ bir liste.", "Adını koyduğun eksik, bu hafta çalışılır."],
 "Serbest cisim diyagramı": ["Cismi bir nokta gibi çiz.", "Üstüne etki eden her kuvveti ok olarak çiz: ağırlık, tepki, sürtünme.", "Oklar hazırsa formül kendiliğinden gelir."],
 "Plan çok ağır": ["Planın yüzde kaçını bitirebiliyorsun?", "Yarısını belki.", "Planı yarıya indiriyoruz. Bitmiş küçük plan, bitmemiş büyük plandan iyidir."],
 "Sınav kaygısı belirtileri": ["Sınav yaklaşınca mide ağrısı, uykusuzluk, öfke artabilir.", "Bunlar tembellik ya da şımarıklık değil, kaygının belirtisi olabilir.", "Uzun sürüyorsa okulun rehber öğretmeniyle görüşün."],
 "Tek kaynak yetmez": ["Beş kaynağın ilk 50 sayfası, bir kaynağın 250 sayfası değildir.", "Bir kaynağı baştan sona bitir.", "Sonra ikincisine geç. Bitmek de öğretir."],
 "Dikkat dağılınca": ["Denemenin ortasında dikkat dağılır. Herkeste olur.", "Kalemi bırak, gözünü kapat, 3 derin nefes.", "30 saniye kaybedip 10 dakika kazanırsın."],
 "Ailene teşekkür": ["Sınav yılında evde herkes biraz senin için yaşıyor.", "Sessizlik, yemek, bekleyiş.", "Bu hafta birine teşekkür et. Tek cümle yeter."],
 "Çalışma saatini sabitle": ["Her gün başka saatte başlamak her gün yeniden karar vermek demek.", "Bir saat seç: mesela 19:00.", "Üç hafta sonra o saat geldiğinde beden kendiliğinden masaya gider."],
 "Periyodik tabloda yön": ["Sağa gittikçe elektronegatiflik artar.", "Yukarı çıktıkça da artar.", "Soy gazlar hariç en elektronegatif: sağ üst köşe, flor."],
 "YKS'ye 150 gün": ["150 gün: 21 hafta.", "Her hafta bir deneme, bir analiz, bir tekrar günü.", "Tempo sabit. Panik yok."],
 "Ödül ve ceza": ["Büyük ödül çocuğu kısa süre heyecanlandırır.", "Sonra kaybetme korkusu başlar, kaygı artar.", "Küçük ve sık takdir daha çok işe yarar: ‘Bu hafta çok düzenliydin.’"],
 "Karne günü": ["Bugün önce sarılın.", "Sonra birlikte bakın: hangi ders yükseldi?", "Düşük notları yarıyıl tatilinde sakin bir planla konuşun."],
 "Kolay soruyu kaçırmak": ["Zor soruyu yapamamak normal.", "Kolay soruyu kaçırmak pahalı.", "Bu denemede kaç kolay soru kaçtı? Onlar en ucuz net."],
 "Uyku borcu": ["Haftanın yorgunluğu uyku borcu olarak birikir.", "Bu gece bir saat erken yat.", "Pazartesi dikkatin fark eder."],
 "Yarıyıl: yılın en değerli 16 günü": ["İlk 3 gün tam dinlenme.", "Sonraki 13 gün: sabah konu, öğlen soru, akşam tekrar.", "Her hafta 2 deneme. Birinci dönemin eksikleri kapansın."],
 "Deney sorularında değişken": ["Deneyde neyi değiştirdiler? Bağımsız değişken.", "Neyi ölçtüler? Bağımlı değişken.", "Neyi aynı tuttular? Kontrol. Üçünü yazınca soru çözülür."],
 "Sınav kaygısı": ["İlk 10 dakika kaygının en yüksek olduğu an.", "Evet, gözüm okuyor ama aklım almıyor.", "İlk 3 dakika sadece kolay soruları işaretle. Beyin ısınınca kaygı düşer."],
 "Beslenme": ["Sabah kahvaltısı dikkatin yakıtı.", "Aç karnına deneme, ilk bir saatten sonra düşer.", "Basit yeter: yumurta, peynir, ekmek, su."],
 "Sabah erken kalkan kazanır": ["Saat 5'te kalkıp öğlen uyuklamak kazandırmaz.", "Her gün aynı saatte kalkmak kazandırır.", "Uykunu değil, düzenini sabitle."],
 "Deneme sıklığı": ["Eylül–ocak: haftada 1 deneme.", "Şubat–nisan: haftada 1 genel, 1 branş.", "Mayıs: haftada 2. Her birinin analizi şart."],
 "Kötü hafta": ["Bu hafta planın yarısı bile olmadı.", "Bir hafta, 40 haftalık yolun küçük bir parçası.", "Yarın küçük bir işle başla. Yeter."],
 # Şubat: ikinci dönem, 6 Şubat, Ramazan, başvuru
 "Yorgunluk haftası": ["Yorgun olduğunu fark etmek iyi bir şey.", "Plan iptal olmaz, yarıya iner.", "Bu hafta uyku ve tekrar. Yeni konu yok."],
 "Tuzak kelimeler": ["‘Yalnızca’, ‘kesinlikle’, ‘her zaman’ biyolojide çoğu zaman yanlıştır.", "Canlılarda istisna çoktur.", "Bu kelimeyi gördüysen şıkkı iki kez oku."],
 "Kitaplar bitmiyor": ["Beş kitabın hiçbiri bitmezse eksikler hep aynı yerde kalır.", "Hangisi en çok işine yarıyor?", "O kalsın, diğerleri rafa. Önce bir kitap bitsin."],
 "Hafta sonu dengesi": ["Pazar günü birkaç saatlik aile gezmesi yasak değil.", "Tersine, beyin dinlenir, hafta daha iyi başlar.", "Tek kural: gezinin saati önceden belli olsun."],
 "Deneme neti = gerçek net": ["Bir denemenin neti o günün fotoğrafı.", "Uyku, zorluk, moral değişir.", "Son üç denemenin ortalaması gerçeğe daha yakın."],
 "6 Şubat": ["6 Şubat 2023.", "Kaybettiğimiz canları rahmetle anıyoruz.", "Yaralarını saran herkese şükranla."],
 "Hedefi küçült": ["Hedef büyük olabilir: tıp, hukuk, mühendislik.", "Ama bugünün adımı küçük olmalı: 40 soru.", "Küçük adımlar birikir, büyük hedefe varır."],
 "İkinci dönem ve Ramazan": ["İkinci dönem başladı, Ramazan da başlıyor.", "Oruçluysan zor dersi sahurdan sonra ya da iftardan bir saat sonra çalış.", "İftardan hemen önce zor soru çözme, tekrar yap."],
 "Anlatım bozukluğu": ["Anlatım bozukluğu sorusunda cümleyi içinden değil sesli oku.", "Kulak tuhaflığı kuraldan önce yakalar.", "Sonra kurala bak: gereksiz kelime mi, yanlış ek mi?"],
 "Paragraf yavaş": ["Kaç dakikada kaç paragraf çözüyorsun, ölçtün mü?", "40 soruya 50 dakika gidiyor.", "Her gün 20 paragraf, süre tutarak. Üç haftada 10 dakika kazanırsın."],
 "YKS başvuru dönemi": ["Başvuru ÖSYM'nin açıkladığı tarihlerde yapılır.", "Kimlik, güncel fotoğraf ve ücret hazır olsun.", "Son güne bırakmayın. Sistem son gün yavaşlar."],
 "Ezber her şeydir": ["Tarih bir hikâye.", "Neden oldu, sonra ne oldu? Bu sırayı bilen tarihi hatırlar.", "Kopuk ezber iki gün sonra uçar."],
 "AYT denemesi": ["AYT, TYT'den uzun ve yorucu.", "Önce en güçlü olduğun testten başla.", "Yanında su ve küçük bir atıştırmalık olsun."],
 "Telefonsuz akşam": ["Bu akşam bir saat telefon başka odada.", "Kitap oku, yürü, ailenle otur.", "Bir saat sonra dön. Kaçırdığın hiçbir şey olmadı."],
 "Deneme haftası planı": ["Deneme olan hafta yeni konu açma.", "Son konuların tekrarı ve soru çözümü yeter.", "Deneme bitince analiz, sonra yeni konu."],
 "Yardımcı çizgi": ["Geometride takıldın mı? Şekle bir şey ekle.", "Bir dikme, bir paralel ya da bir köşegen.", "Çoğu soru bir çizgiyle üçgene dönüşür."],
 "Ezberim uçuyor": ["İki gün sonra unutmak beynin normal hâli.", "O zaman boşuna mı çalışıyorum?", "Hayır: 1 gün, 3 gün, 7 gün sonra kısa tekrar yap. Kalıcı olur."],
 "Öğretmenle iletişim": ["Çocuğunuz uzun süre isteksiz, uykusuz ya da içine kapanıksa.", "Ya da notlarında ani bir düşüş varsa.", "Okulun rehber öğretmeni ilk ve ücretsiz kapıdır."],
 "Koç = öğretmen": ["Öğretmen konuyu anlatır.", "Koç planı kurar, takip eder, tıkandığında yolu değiştirir.", "İkisi birbirinin yerine geçmez, birbirini tamamlar."],
 "Deneme karşılaştırma": ["Arkadaşınla netini kıyaslamak seni yorar.", "Kendi dünkü netinle kıyasla.", "Ondan iyiysen doğru yoldasın."],
 "İyi ki çalıştın": ["Bu hafta yorulduysan, çalıştığın içindir.", "Yorgunluk emeğin izidir.", "Bu akşam dinlen. Hak ettin."],
 "Plan ile program farkı": ["Okulun ders programı sana verilen bir çizelge.", "Senin planın, o programın boşluklarını nasıl kullandığın.", "Programı değiştiremezsin, planı değiştirebilirsin."],
 "Oran orantı": ["a/b = 2/3 ise a = 2k, b = 3k de.", "Bütün bilinmeyenler tek bir k'ye bağlanır.", "Sonra k'yi bul. Oran sorusu bitti."],
 "Kardeşim gürültü": ["Evde sessiz bir saat bulmak zor olabilir.", "Kardeşim akşamları hep oyun oynuyor.", "Ailenle bir saat kararlaştır: 19–21 ev sessiz. Kulaklık da işe yarar."],
 "Ekran süresi": ["Telefonu tamamen yasaklamak gizli kullanımı artırır.", "Birlikte saat koyun: ders saatinde başka odada.", "Akşam bir saat serbest. Kural ikiniz için de geçerli olsun."],
 "Yanlış soruya bakılmaz": ["Yanlış yaptığın soru sana eksiğini gösterir.", "Ona bakmamak, aynı yanlışı sınavda tekrar yapmak demek.", "Her denemeden 5 yanlış: nedenini yaz."],
 "Konu eksiği mi, dikkat mi": ["Yanlışlarını iki sütuna ayır.", "Bilmediğin konular: bu haftanın çalışma listesi.", "Dikkat hataları: soruyu iki kez okuma alışkanlığı."],
 "Pes etmek istemek": ["Bir noktada ‘bıraksam’ diye düşünmek çok normal.", "Bu düşünce geldiğinde karar verme, sadece dinlen.", "Ertesi gün hâlâ aynı düşünüyorsan, biriyle konuş."],
 # Mart: bayram, 100 gün, bahar
 "Sınavdan geriye plan": ["Sınava 16 hafta kaldı.", "Son 4 hafta: sadece deneme ve tekrar.", "Geriye kalan 12 hafta: eksik konular. Takvime yaz."],
 "Neden–sonuç zinciri": ["Tarih sorusu çoğu zaman ‘neden’ ya da ‘sonucu nedir’ diye sorar.", "Her olay için üç kutu çiz: sebep, olay, sonuç.", "Kutular dolunca soru kolaylaşır."],
 "Bayram çalışması": ["Bayramda hiç çalışmasan da dünya yıkılmaz.", "Ama bir hafta hiç dokunmazsam korkuyorum.", "O zaman bayramda her gün 1 saat. Sabah, misafirlerden önce."],
 "Bayram ziyaretleri": ["Bayramda en çok sorulan soru: ‘Kaç net yapıyorsun?’", "Çocuğunuz her seferinde bir sınav gibi hisseder.", "‘Çok çalışıyor, bayramda dinleniyor’ demeniz yeter."],
 "Bayramda çalışılmaz": ["Bayramda üç gün çalışmamak kimseyi geri bırakmaz.", "Asıl risk, bayramdan sonra dönememek.", "Bayram bitince ilk gün, küçük bir planla başla."],
 "Bayram denemesi": ["Uzun tatilin bir gününü deneme günü yap.", "Sınav saatinde başla, sınav gibi çöz.", "Kalan günler dinlenme ve kısa tekrar."],
 "Yavaş ilerleme": ["Netin her hafta artmıyor diye durduğunu sanma.", "Temel oturuyor, artış sonra gelir.", "Yavaş ilerlemek durmaktan iyidir."],
 "Arife ve ara tatil": ["Bayram ve ara tatil birleşti: 9 gün.", "Her gün bir saat kural: sabah, kısa tekrar.", "Bir gün de deneme. Gerisi bayram."],
 "Ramazan Bayramı": ["Bayramınız mübarek olsun.", "Bugün aile, sofra ve dinlenme günü.", "Yarın her gün bir saat kuralı devam."],
 "Son 100 gün paniği": ["Yetişmeyecek diye düşündüğün şey ne?", "Fizik ve geometri daha bitmedi.", "100 günde ikisine birer ay. Kalan zaman tekrar. Yetişir."],
 "YKS'ye 100 gün": ["100 gün kaldı. Yeni konu yavaşlıyor.", "Eksik konulara son 6 hafta, sonra tekrar ve deneme.", "Her gün aynı ritim. Panik değil, tempo."],
 "Uyku kaybıdır": ["Uyku sırasında beyin gün içinde öğrendiklerini kaydeder.", "Az uyuyan öğrenci öğrendiğinin bir kısmını kaybeder.", "7–8 saat uyku, çalışmanın bir parçasıdır."],
 "Deneme sonrası ödül": ["Deneme bitince bir saat tamamen boş.", "Yürü, müzik dinle, bir arkadaşınla konuş.", "Analiz bir saat sonra, taze kafayla."],
 "Kendini affet": ["Bu hafta planladıklarının hepsini yapamadın.", "Kendine kızmak bir sonraki haftayı da bozar.", "Affet, küçük bir planla yeniden başla."],
 "Kırmızı kutular": ["Yapılmayan iş silinmez.", "Ya bir sonraki güne taşınır ya da küçülür.", "Planındaki kırmızı kutuları her pazar akşamı yeniden yerleştir."],
 "Filozof–kavram eşlemesi": ["Kavramı tek başına ezberleme.", "Filozofun ağzından bir cümle kur: ‘Descartes: Düşünüyorum, öyleyse varım.’", "Cümle akılda kalır, kavram onunla gelir."],
 "Dershane mi, evden mi": ["Etüt sana ne kazandırır, önce onu düşün.", "Evde dikkatim dağılıyor.", "O zaman haftada iki gün etüt, diğer günler evde düzen. Deneyip bakarız."],
 "Hedef konuşması": ["Çocuğunuzun hedefi sizin hayaliniz olabilir.", "Kendi seçmediği hedefe çalışmak çok daha zor.", "Önce onu dinleyin: ne okumak istiyor, neden?"],
 "Sosyal hayat bitmeli": ["Bir yıl boyunca arkadaşsız kalmak yalnızlığı artırır.", "Yalnızlık da odağı azaltır.", "Haftada bir kez biriyle buluş. Ders konuşmadan."],
 "Zor deneme": ["Deneme zor geldiyse herkese zor geldi.", "Sıralaman netinden daha doğru bilgi verir.", "Zor denemenin analizi, kolay denemeninkinden çok şey öğretir."],
 "Gün geceyi geçti": ["Gece ile gündüz eşitlendi.", "Yarından itibaren gündüz daha uzun.", "Işık uzuyor. Enerji de onunla artar."],
 "Sabah 20 dakika": ["Okuldan önce 20 dakika paragraf.", "Günün en taze saatinde, en kolay kazanç.", "Bir ayda 400 paragraf eder."],
 "Limitte belirsizlik": ["Limitte 0/0 gördüysen ilk refleks çarpanlara ayırmak.", "Ortak çarpanı sadeleştir.", "Olmuyorsa eşleniğiyle çarp. Çoğu soru bu ikisinden biri."],
 "Hafta sonu kaçtı": ["Utanmana gerek yok. Hafta sonu kaçtı, hafta kaçmadı.", "Ama pazartesi hiç başlayasım yok.", "Bugün sadece planın ilk işini yap. Gerisi kendiliğinden gelir."],
 "Kötü gün": ["Çocuğunuz ‘bugün hiç çalışmadım’ dediyse, bunu söyleyebilmesi güvenin işareti.", "Kızmak bir sonraki sefer saklamasına yol açar.", "‘Yarın ne yapacaksın?’ diye sormanız yeter."],
 "Paragraf yeteneğe bağlı": ["Paragrafta hızlı olanlar doğuştan hızlı değil.", "Her gün paragraf çözen hızlanır.", "Günde 20 paragraf, bir ayda fark eder."],
 "Paragraf süresi": ["Bu denemede paragrafa kaç dakika harcadın?", "Hedef: soru başına bir dakikanın altı.", "Fazlaysa önce soru kökünü okuma alışkanlığını dene."],
 "Plan hazırlığı": ["Yarının ilk işini bu akşam yaz.", "Sabah ‘ne yapsam’ diye düşünmeden başlarsın.", "İlk iş bitince gün kendiliğinden yürür."],
 "Yatmadan 10 dakika": ["Yatmadan önce 10 dakika: bugün yanlış yaptığın 3 soru.", "Doğru çözümü bir kez daha oku.", "Uyku onları senin için kaydeder."],
 "Grafik yorumlama": ["Grafik sorusunda önce eksenleri oku: ne ölçülüyor, birimi ne?", "Sonra çizginin nerede arttığına, nerede azaldığına bak.", "Soruyu grafiğe değil, sorunun sorduğuna göre oku."],
 "Net takıldı": ["Net üç hafta aynı kalıyorsa yöntem değişmeli.", "Hep aynı şekilde çalışıyorum ama.", "Bu hafta konu değil yanlış analizi yapıyoruz. Net oradan açılır."],
})

# ── 1 Nisan – 30 Haziran 2027 (sınav dönemi) ──────────────────────
GOVDE.update({
 # Nisan: bahar yorgunluğu, net platosu
 "Deneme maliyeti": ["Her hafta ücretli deneme almak şart değil.", "Okulun, MEB'in ücretsiz denemeleri ve elinizdeki kitaplar yeter.", "Önemli olan denemenin sayısı değil, analizi."],
 "Son ay her şeyi değiştirir": ["Son ay yeni konu öğrenme ayı değil.", "Son ay bildiklerini hızlandırma ve sağlamlaştırma ayı.", "Eksik konuların nisanda bitmeli."],
 "Sınav provası": ["Bu cumartesi denemeye tam 10.15'te başla.", "Aynı kahvaltı, aynı kalem, aynı su.", "Beden sınav saatine şimdiden alışsın."],
 "Bahar huzursuzluğu": ["Hava ısınınca içeride oturmak zorlaşır. Çok normal.", "Günde bir saat dışarı çık, yürü, güneş al.", "Dönünce masaya daha kolay oturursun."],
 "Konu bitirme yanılgısı": ["Konu anlatımını bitirmek konuyu bitirmek değil.", "O konudan 100 soru çözdüğünde bitti say.", "Soru çözmeden ‘bitti’ yazma."],
 "Elektrikte eşdeğer direnç": ["Karışık devreyi düz bir çizgi gibi yeniden çiz.", "Önce paralel kolları tek dirence indir.", "Sonra seri olanları topla. Devre sadeleşir."],
 "Bahar yorgunluğu": ["Bahar yorgunluğu gerçek bir şey. Beden mevsime alışıyor.", "O zaman ne yapayım?", "Bu hafta planı yüzde 20 küçült, her gün 30 dakika yürü. Ritim geri gelir."],
 "Kardeşler": ["Sınava hazırlanan çocuk evin merkezine oturabilir.", "Küçük kardeş de ilgi ister, kıskanabilir.", "Ona da ayrı bir zaman ayırın. Evdeki denge herkese iyi gelir."],
 "Matematik kafası": ["‘Matematik kafası’ diye bir şey yok.", "Matematik tekrar ve soruyla oturur.", "Her gün 30 soru, üç ayda başka bir sen."],
 "Deneme sonucu paylaşmak": ["Netini herkese söylemek zorunda değilsin.", "Kıyas senin motivasyonunu yer.", "Netini koçunla ve kendinle paylaş, yeter."],
 "Sınav yaklaşırken": ["Sınav yaklaştıkça günler hızlanıyor gibi gelir.", "Ama her gün yine 24 saat.", "Takvime değil, bugünün planına bak."],
 "Haftalık net hedefi": ["Bu hafta hedefin +1 net.", "Hangi dersten? En kolay açılacak olandan.", "Küçük ama gerçek artışlar birikir."],
 "Tepkime denkleştirme": ["Önce en çok atom içeren molekülü seç.", "Onun atomlarını karşı tarafta eşitle.", "En son oksijen ve hidrojen. Sıra hep bu."],
 "Kıyaslanmak": ["Kıyaslanmak insanı yorar, öfkelendirir. Bu çok anlaşılır.", "Ne diyeceğimi bilmiyorum.", "‘Bana kendi ilerlememe göre bakar mısın?’ de. Netlerini ona sen göster."],
 "Övgü": ["‘Aferin, zekisin’ çocuğa zekâsını kaybetme korkusu verir.", "‘Aferin, çalıştın’ ise emeğini görür.", "Emeği övülen çocuk zor işten kaçmaz."],
 "Herkes 14 saat çalışıyor": ["Sosyal medyadaki masa fotoğrafı bir anın fotoğrafı.", "Molaları, yorgunluğu, kötü günleri görünmez.", "Kendi gününü onlarınkiyle değil, dününle kıyasla."],
 "Yorgun deneme": ["Yorgun çözdüğün deneme gerçek seviyeni göstermez.", "Yorgunluğun seviyesini gösterir.", "Deneme günü önceki gece erken yat."],
 "Gurur": ["Eylülden bu yana ne değişti?", "İlk denemendeki netine bir bak.", "O farkla gurur duy. Sen yaptın."],
 "Ders geçişleri": ["Aynı dersi üç saat çalışmak beyni yorar.", "Sayısaldan sonra sözele geç.", "Beyin dinlenir, sen çalışmaya devam edersin."],
 "Kalıtımda çaprazlama": ["Çaprazlamada tahmin yürütme, tablo kur.", "Anne gametlerini üste, baba gametlerini yana yaz.", "Kutuları doldur. Oranlar tablodan okunur."],
 "Her şeyi bıraktım": ["Futbol sana ne veriyordu?", "Kafamı boşaltıyordu.", "O zaman haftada bir maça geri dön. Kafası boşalan daha iyi çalışır."],
 "Sessizlik": ["Çocuğunuz son günlerde az konuşuyorsa, üstüne gitmeyin.", "Yanında sessizce oturmak, bir çay götürmek kapıyı açık tutar.", "Konuşmaya hazır olduğunda size gelir."],
 "23 Nisan": ["23 Nisan Ulusal Egemenlik ve Çocuk Bayramı kutlu olsun.", "Bugün LGS'ye hazırlanan çocuklarımızın da bayramı.", "Bugün ders değil, oyun ve bayram."],
 "Kalem ve silgi": ["Sınav günü yeni kalem denemek risk.", "Kullanacağın kalemi ve silgiyi bugünden seç.", "Kalan tüm denemeleri onlarla çöz."],
 "Karşılaştırma tuzağı": ["Sosyal medyada herkes en iyi anını paylaşır.", "Kötü günler, boş masalar görünmez.", "Bu hafta o hesapları biraz sessize al."],
 "Uyku saati planın parçası": ["Uyku saatin sabit değilse sabahın da sabit olmaz.", "Her gece aynı saatte yat.", "Son ay uyku saati sınav sabahına göre olsun."],
 "İklim grafikleri": ["İklim grafiğinde önce yağışın hangi mevsimde yoğunlaştığına bak.", "Sonra sıcaklık farkına bak.", "Kışın yağış, yazın kuraklık: Akdeniz."],
 "Soru çözerken dalıyorum": ["Dalmak dikkatin yorulduğunu söyler.", "Ama daha yeni oturuyorum.", "Telefon başka odada mı? 25 dakikalık bloklarla dene. Dalma azalır."],
 "Koçluk nedir": ["Koç ders anlatmaz.", "Haftalık planı kurar, her gün takip eder, denemeleri birlikte analiz eder.", "Tıkandığında yolu değiştirir. Öğrenci yalnız kalmaz."],
 "YKS'ye 50 gün": ["50 gün: 7 hafta.", "Her gün bir analiz, haftada iki deneme.", "Yeni konu değil, bildiklerini hızlandırma zamanı."],
 # Mayıs: son düzlük, uzun bayram
 "Son denemeler": ["Son üç denemede yeni bir strateji deneme.", "Bildiğin sıra, bildiğin süre.", "Amaç şaşırmamak."],
 "Sabır": ["Net artışı bazen haftalarca düz gider.", "Sonra birden yükselir.", "Düz giden haftalar boşa değil, temel oturuyor."],
 "Çalışma yerini değiştir": ["Yatakta çalışan beyin uykuya hazırlanır.", "Masa, ışık, sandalye: beyin oraya iş diye bakar.", "Bu hafta sadece masada çalış."],
 "Sözcükte anlam": ["Sözcüğü cümleden çıkar.", "Yerine şıklardaki anlamı koy.", "Cümle bozulmuyorsa doğru şık o."],
 "Sabah kalkamıyorum": ["Alarmı ertelemek sabahı daha ağır yapar.", "Ne yapayım?", "Alarmı yataktan uzak koy, kalkınca ışığı aç. Üç günde alışırsın."],
 "Uzun hafta sonu": ["Kurban Bayramı ve 19 Mayıs art arda: beş günlük tatil.", "İlk iki gün aile ve bayram.", "Kalan günlerde her sabah 3 saat tekrar ve bir deneme."],
 "Son hafta yeni konu": ["Son hafta yeni konuya başlamak kaygıyı artırır.", "Bilmediğin bir konu sınavda 1–2 soru.", "Bildiklerini sağlamlaştırmak çok daha fazlasını getirir."],
 "Soru atlama cesareti": ["Bu denemede bilerek 3 zor soruyu atla.", "Sonra bak: süre ne kadar arttı, net ne oldu?", "Atlamak kaybettirmez, zaman kazandırır."],
 "Anneler Günü": ["Sınav yılında evde en az görünen koç: anneler.", "Sabah kahvaltısı, sessiz ev, bekleyen bir göz.", "Anneler Günü kutlu olsun."],
 "Biriken ödev": ["Okul ödevleri birikince kafa YKS'ye de gitmez.", "Önce ödevi bitir, aklından çıksın.", "Sonra plana dön, rahat bir kafayla."],
 "Mutlak değer": ["Mutlak değerin içi pozitif ya da negatif olabilir.", "Her zaman iki durum yaz.", "İki çözümü de kontrol et."],
 "Yanlış yapmaktan korkuyorum": ["Boş bıraktığın soruların kaçını aslında biliyordun?", "Sanırım yarısını.", "İki şıkka indirdiysen işaretle. Korku sana yarım net kaybettiriyor."],
 "Haftalık görüşme": ["Haftada bir 15 dakika çocuğunuzla oturun.", "Soru sormayın, sadece dinleyin.", "Anlattığı şeyler size çok şey söyler."],
 "Yazılı notları önemsiz": ["Okul notları diploma notunu, o da OBP'yi belirler.", "OBP YKS puanına eklenir.", "Yazılılar da sınavın parçası."],
 "Kurban arifesi: 5 günlük ara": ["5 gün tatil: ilk 2 gün aile ve bayram.", "Sonraki 3 gün her sabah 3 saat tekrar.", "Bir gün de deneme. Sonra dinlen."],
 "Kurban Bayramı": ["Kurban Bayramınız mübarek olsun.", "Bugün aile, büyükler ve dinlenme günü.", "Sınava bir ay kaldı. Bayram da hazırlığın parçası."],
 "Hafta ortası kontrolü": ["Çarşamba akşamı 5 dakika: planın ne kadarı bitti?", "Geride kaldıysan perşembeyi hafiflet.", "Hafta sonu yığılmaz."],
 "Diyalog sorusu": ["Diyalogda boşluktan sonraki cümleye bak.", "Cevap çoğu zaman o cümleyle bağlanır.", "Şıkları boşluğa koyup yüksek sesle oku."],
 "19 Mayıs": ["19 Mayıs Atatürk'ü Anma, Gençlik ve Spor Bayramı kutlu olsun.", "Bu yıl sınava giren gençler, bu bayram sizin.", "Bugün biraz hareket et. Spor da hazırlığın parçası."],
 "YKS'ye 30 gün": ["30 gün kaldı.", "Uyku saatini sınava göre ayarla: 23'te yatış, 7'de kalkış.", "Denemeleri 10.15'te başlat."],
 "Soru atlamak zayıflık": ["Zor soruya takılmak kolay soruları kaybettirir.", "Atla, işaretle, sona dön.", "Soru atlamak strateji, zayıflık değil."],
 "Denemeden plan çıkar": ["Denemedeki üç en büyük eksik, pazartesinin planı.", "Konu eksiği mi? O konudan 40 soru.", "Dikkat hatası mı? Soru kökünü iki kez okuma alışkanlığı."],
 "Anlam": ["Bu yıl sadece bir puan için değildi.", "Her gün masaya oturmayı öğrendin.", "Bu disiplin sınavdan sonra da seninle kalacak."],
 "Mola planlanır": ["Plansız mola bir saate uzar.", "Planlı mola 10 dakikadır.", "Molayı plana yaz: saat, süre, ne yapacağın."],
 "Üçgende benzerlik": ["Şekilde paralel doğru gördüysen benzer üçgen ara.", "Karşılıklı kenarları eşleştir.", "Oran kur, bilinmeyeni bul."],
 "Bir ders çok geride": ["Kimyanın tamamını bu ay bitiremeyiz.", "O zaman ne yapacağım?", "En çok soru gelen 4 konuyu seç. Kalan zamanı onlara ver."],
 "Okul mu YKS mi": ["Okul notları ve YKS birbirinin rakibi değil.", "Yazılı haftasında önce okul, her gün kısa YKS tekrarı.", "İkisi de puana eklenir."],
 "Tekrar sıkıcıdır": ["Tekrar yeni bir şey öğretmiyor gibi gelir.", "Ama sınav günü hatırladığın her şey tekrar sayesinde.", "Tekrar sıkıcı değil, kalıcı."],
 "Deneme korkusu": ["Deneme bir antrenman.", "Kötü geçmesi, sınavda neyi düzelteceğini gösterir.", "Korkma. Her deneme sınav gününü kolaylaştırır."],
 "Arkadaşlık": ["Sınava az kaldı, arkadaşlarını da unuttun belki.", "Bir tanesini ara, 10 dakika konuş.", "Ders konuşmadan. İkinize de iyi gelir."],
 "Kolay işle başla": ["Masaya oturunca en zor işle başlamak zor gelir.", "İlk 10 dakika 10 kolay soru.", "Motor ısınınca zor olan kolaylaşır."],
 # Haziran: sınav ayı
 "İntegral alan": ["Alan sorusunda önce grafiği çiz.", "Eğrinin eksenin altında kaldığı yeri işaretle.", "Altta kalan parçanın integralini eksiyle al."],
 "Yorgunum": ["Dinlenmek de işin parçası. Suçluluk duymana gerek yok.", "Ama dinlenirken hep ders aklımda.", "O zaman dinlenmeyi plana yaz. Planda olan şey suçluluk getirmez."],
 "Sınav günü": ["Sınav sabahı az konuşun, çok gülümseyin.", "Kimlik, giriş belgesi, kalem: bir gece önceden hazır.", "‘Ne olursa olsun seninle gurur duyuyoruz’ deyin, yeter."],
 "Dinlenmek suç": ["Son haftalarda dinlenmek tembellik değil.", "Yorgun beyin bildiğini de unutur.", "Her gün bir saat tamamen boş zaman."],
 "Net düşüşü": ["Son denemede netin düştüyse panikleme.", "Deneme mi zordu, sen mi yorgundun? İkisine de bak.", "Tek deneme bir şey söylemez. Son üçün ortalamasına bak."],
 "Son pazar": ["Sınavdan önceki son pazarlardan biri.", "Bugün sakin bir gün olsun: kısa tekrar, yürüyüş, erken uyku.", "Bildiklerin seninle."],
 "Plan paylaşılır": ["Planını birine söylemek onu gerçek yapar.", "Ailene ya da bir arkadaşına söyle.", "‘Bugün bunu yapacağım’ demek bile işe yarar."],
 "Şiir bilgisi": ["Ölçü sorusunda heceleri kalemle işaretle.", "Açık ve kapalı heceyi ayır.", "Parmakla saymak kolay şaşırtır."],
 "YKS'ye 10 gün": ["10 gün kaldı. Yeni hiçbir şey öğrenme.", "Bildiklerini tekrar et, iki deneme çöz.", "Uyku, su, yürüyüş. Hazırsın."],
 "Harçlık ve bağımsızlık": ["Sınav yılında çocuğun sorumlulukları azalabilir.", "Ama tamamen kaldırılmasın.", "Kendi masasını düzenlemek, kendi çantasını hazırlamak da hazırlıktır."],
 "Bir kötü deneme her şeyi söyler": ["Son denemede kötü geçmesi sınavın kötü geçeceği anlamına gelmez.", "Tek deneme trend değil.", "Son beş denemenin çizgisine bak."],
 "LGS'ye bir gün": ["Yarın LGS.", "Bu akşam çanta hazır: kimlik, kalem, silgi, su.", "Erken yemek, erken yatak. Başka hiçbir şey."],
 "LGS günü": ["Bugün 8. sınıfların günü.", "Sonuç ne olursa olsun, bu yıl çok emek verdiler.", "Sınavdan çıkınca soruyu değil, onları sorun: nasılsın?"],
 "Her şey acil değil": ["Sınava bir hafta kala her ders acil gibi gelir.", "Sıra koy: en çok soru gelen konular önce.", "Geri kalanı hızlı tekrar."],
 "Grafik okuma": ["Hız–zaman grafiğinde eğim ivmeyi verir.", "Grafiğin altındaki alan yolu verir.", "Önce eksenleri oku: hız mı, konum mu?"],
 "Sosyal medya kıyası": ["Sınava bir hafta kala başkalarının masasına bakmak seni yorar.", "Ama herkes çok çalışıyor gibi.", "Bu hafta sosyal medyayı kapat. Sadece kendi planın."],
 "Sağlık kontrolü": ["Sınav öncesi gözlük ve uyku kontrolü unutulmasın.", "Bulanık görme ve uykusuzluk dikkati düşürür.", "Küçük bir kontrol sınav gününü rahatlatır."],
 "Yarın TYT": ["Yarın TYT.", "Bu gece çalışma. Çantanı hazırla: kimlik, giriş belgesi, kalem, su.", "Erken yat. Sabah her şey yerinde."],
 "TYT günü": ["Bugün hazırlığın konuşuyor.", "Kolay sorularla başla, takıldığında geç.", "Bittiğinde arkana bakma. Yarın AYT."],
 "AYT günü ve Babalar Günü": ["Bugün son oturum.", "Dün ne olduysa oldu, bugün yeni bir sınav.", "Ve bugün Babalar Günü. Bu yıl yanında olan bütün babalara."],
 "Sınav bitti": ["Sınav bitti. Bu yılın emeği bitmedi, seninle.", "Birkaç gün hiçbir şey yapma.", "Sonuç beklemek de zor bir iş. Kendine iyi bak."],
 "Asit–baz": ["pH sorusunda önce H⁺ derişimini bul.", "Asit mi, baz mı? Hangisi fazla?", "Nötrleşmede mol sayılarını eşitle."],
 "Deneme sınavı stresi": ["Yarın deneme var, midem şimdiden ağrıyor.", "Bu stres bedenin hazırlanması.", "Bu akşam hafif ye, erken uyu. Sabah nefes: 4 al, 4 tut, 4 ver."],
 "Başarısızlık korkusu": ["Sonuçlar gelmeden önce kendinize sorun: kazanamazsa ne olur?", "Cevabınız sakinse, çocuğunuza da sakinlik geçer.", "Her sonuç bir sonraki adımın başlangıcı."],
 "Karne ve 11. sınıflar": ["11. sınıf bitti. YKS 2028'e bir yıl kaldı.", "Yaz tembellik değil, hazırlık zamanı.", "Her gün bir saat TYT temeli. Eylülde farkını göreceksin."],
 "Fen sırası": ["Fen testinde hangi dersten başlıyorsun?", "Güçlü olduğun dersten başla, güven kazan.", "Sırayı yaz ve bütün denemelerde aynı sırayla git."],
 "Hayır demek": ["Bu hafta bir şeye hayır dedin: bir davete, bir diziye.", "O hayır, hedefine evet dedi.", "Hayır demek de bir beceri."],
 "Soru bankası seçimi": ["Yeni dönem için bir soru bankası seç.", "Üç kitaba birden başlama.", "Bir kitap bitsin, sonra ikincisi."],
 "Sistemler": ["Sistemleri organ organ ezberleme.", "Görevle çalış: sindirim ne yapar, hangi organ ne katar?", "Görev bilince organ kendiliğinden gelir."],
 "Başaramazsam": ["Sonuç ne olursa olsun, bir sonraki adım var.", "Ya olmazsa?", "O zaman birlikte yeni bir plan kurarız. Bu yıl öğrendiğin hiçbir şey kaybolmaz."],
})

# ── 1 Temmuz – 18 Eylül 2027 (sonuç, tercih, yaz, YKS 2028) ────────
GOVDE.update({
 # Temmuz
 "11. sınıf velisi": ["11. sınıf bitti, önümüzde YKS yılı var.", "Yaz tatilinde her gün bir saat TYT temeli yeter.", "Eylülde başlayan değil, temmuzda ısınan rahat eder."],
 "Mezun yılı kolay": ["Mezun yılında zaman bol, ama düzen yok.", "Okul saati yok, arkadaş yok, yalnızlık çok.", "Sabah kalkış saati ve haftada bir sosyal gün şart."],
 "Yaz denemesi": ["Yazın her hafta deneme gerekmez.", "Ayda iki deneme formu korur.", "Deneme günü sınav saatinde başla."],
 "Duygu günlüğü": ["Bugün nasıl hissettin? Tek kelime yaz.", "Bir hafta sonra kelimelere bak.", "Hangi günler iyi, hangi günler zor? Kendini tanırsın."],
 "Yaz planı": ["Yaz tatili dinlenmek için.", "Ama her gün bir saat: sabah, serinken.", "Eylülde sıfırdan değil, ısınmış başlarsın."],
 "İnkılap tarihi kronolojisi": ["Kongreleri tek tek değil, bir yolculuk gibi anlat.", "Amasya, Erzurum, Sivas: karar, toplanma, birlik.", "Hikâye akılda kalır, sıra onunla gelir."],
 "Yalnız hissediyorum": ["Sınav yılı insanı yalnızlaştırabilir. Bunu fark etmen önemli.", "Arkadaşlarımla uzun zamandır görüşmedim.", "Bu hafta birine yaz. Yalnızlık uzun sürerse bir rehber öğretmenle konuş."],
 "Yıl sonu değerlendirme": ["Yıl bitti. Önce puanı değil, yolu konuşun.", "Neyi iyi yaptı? Nerede zorlandı?", "Sonraki adım o konuşmadan çıkar."],
 "Kolay soru herkese kolay": ["Kolay soruyu herkes yapar diye düşünme.", "Acele eden onu kaçırır.", "Kolay soruyu kaçırmamak, zor soruyu yapmaktan değerlidir."],
 "Sınav sabahı kahvaltı": ["Sınav sabahı ağır kahvaltı dikkati düşürür.", "Alışık olduğun hafif kahvaltı: yumurta, peynir, ekmek, su.", "Çantaya su ve küçük bir atıştırmalık koy."],
 "Hafta puanı": ["Haftana 10 üzerinden kaç verirsin?", "6 iyi bir not. Mükemmel hafta yok.", "Bir sonraki hafta 7 olsun, o kadar."],
 "Kaynak bitirme": ["Bu ay bitireceğin tek kaynağı seç.", "Her gün birkaç sayfa, ay sonunda bitmiş bir kitap.", "Bitmiş kitap, yarım kalmış beş kitaptan iyidir."],
 "Çarpanlar ve katlar": ["Bir şeyi parçalara bölüyorsan EBOB.", "Parçaları birleştirip ortak bir an arıyorsan EKOK.", "Soruyu okuyunca önce bunu sor: bölüyor muyum, buluşturuyor muyum?"],
 "Sonuç haftası": ["Sonuçlara birkaç gün kaldı.", "Bekleme kaygısı çok normal.", "Bu hafta yürü, uyu, sevdiğin şeyleri yap. Sen dinlenebilirsin."],
 "15 Temmuz": ["15 Temmuz Demokrasi ve Millî Birlik Günü.", "Hayatını kaybedenleri rahmetle anıyoruz.", "Gazilerimize şükranla."],
 "Formül ezberi yeter": ["Formülü bilmek soruyu çözmeyi garanti etmez.", "Formül ne zaman, nasıl kullanılır? Asıl bilgi bu.", "Her formül için üç farklı soru çöz."],
 "Net hedefi gerçekçi": ["Bir sonraki denemede +20 net hedeflemek hayal kırıklığı getirir.", "+2 net gerçekçi.", "Küçük artışlar birikir, büyük farkı onlar yapar."],
 "Kendi hızın": ["Herkes aynı hızda ilerlemez.", "Senin saatin de işliyor, sadece farklı bir tempoda.", "Kendi temponu koru."],
 "Plan şişmesi": ["Plana her gün bir şey ekliyorsan liste yapıyorsun.", "Plan bitirilebilecek kadar küçüktür.", "Bu hafta plandan üç şey çıkar."],
 "Sonuçlar açıklandı": ["Sonuçlar açıklandı. Önce derin bir nefes.", "Beklediğin gibi ya da değil, bu bir sayı.", "Senin bu yılın, emeğin ve öğrendiklerin o sayıdan büyük."],
 "Tercih kaygısı": ["Önce sıralamana bak, sonra ilgi alanına.", "Hangi bölümü sevdiğimi bile bilmiyorum.", "Üç bölümün ders içeriğine bak, o bölümde okuyan biriyle konuş. Karar netleşir."],
 "Tercih dönemi": ["Tercih listesini çocuğunuz yazmalı, siz destek olmalısınız.", "Sizin hayalinizdeki bölüm onun dört yılı olacak.", "Soru sorun, dinleyin, zorlamayın."],
 "Tercihte puan her şey": ["Puan kapıyı açar, ama hangi kapı olduğu önemli.", "Şehir, bölüm, burs, ilgi: hepsi listede.", "En yüksek puanlı bölüm en doğru bölüm değildir."],
 "Deneme stresi bedende": ["Deneme öncesi karın ağrısı ve terleme normal.", "4 saniye nefes al, 4 tut, 4 ver.", "Üç tekrar, beden sakinleşir."],
 "Bedenin sinyali": ["Başın ağrıyor, gözün yanıyor mu?", "Beden dur diyor.", "Mola ver, su iç, ekrandan uzaklaş. Yarın daha iyi çalışırsın."],
 "Sabah mı, akşam mı?": ["Bazı insanlar sabah, bazıları akşam daha iyi odaklanır.", "Bir hafta dene: sabah bir saat, akşam bir saat.", "Hangisinde daha çok soru çözdüğüne bak."],
 "Tercih dönemi başladı": ["Tercih dönemi başladı.", "Listeyi son güne bırakmayın, sistem son gün yavaşlar.", "Liste çocuğun, destek sizin."],
 "Öğretmenim kırdı": ["Bunu duymak çok kırıcı olmalı.", "Evet, herkesin önünde söyledi.", "Onun cümlesi seni ölçmez. İstersen rehber öğretmenle de konuşabiliriz."],
 "Evde deneme günü": ["Cumartesi deneme günü evde sessizlik yeter.", "Kahvaltı hazır, televizyon kapalı.", "Deneme bitince ‘kaç net’ yerine ‘nasıldı’ diye sorun."],
 "TYT kolay, AYT önemli": ["TYT neti yalnız TYT puanını değil, AYT puanını da etkiler.", "TYT'yi ihmal eden AYT'de de kaybeder.", "İkisi birlikte çalışılır."],
 "Kodlama zamanı": ["Optiği en sona bırakmak risklidir.", "Her 10 soruda bir optiği doldur.", "Son 5 dakikada panik olmaz."],
 # Ağustos
 "Umut": ["Umut güzel, ama tek başına yetmez.", "Umudun yanına bir plan koy.", "Plan umudu gerçek yapar."],
 "Hafta sonu yükü": ["Hafta içi kaçan işleri hafta sonuna yığma.", "Hafta sonu dinlenemezsen pazartesi yorgun başlarsın.", "Kaçanı hafta içine dağıt."],
 "Paragrafta ana düşünce": ["Ana düşünce çoğu zaman ilk ya da son cümlede.", "Önce bu iki cümleyi oku.", "Şıklardan hangisi ikisini de kapsıyor? O cevap."],
 "Program bozuldu": ["Misafir geldi, gün gitti. Olur.", "Ama bütün planım bozuldu.", "Bugün 20 soru yeter. Yarın normal plana döneriz."],
 "Bütçe": ["Pahalı kaynak başarı getirmez.", "Bitirilen kaynak getirir.", "Az ve doğru seçilmiş kitaplar yeter."],
 "Ortalama öğrenci kazanamaz": ["Ortalama bir öğrenci düzenli çalışırsa çok yol alır.", "Zeki ama düzensiz öğrenci ise zorlanır.", "Düzen, zekânın açığını kapatır."],
 "Kontrol turu": ["Denemenin son 5 dakikası kontrol için.", "Sadece boş bıraktığın sorulara bak.", "Yaptıklarını ancak açık bir hata görürsen değiştir."],
 "Dua, niyet, dilek": ["Bu hafta için tek bir dileğin ne?", "Bir kâğıda yaz.", "Sonra onun için yapabileceğin tek bir şeyi yanına ekle."],
 "İlk 3 gün kuralı": ["Yeni bir plana başlamak ilk üç gün zor.", "Dördüncü gün alışkanlık başlar.", "İlk üç günü kolay tut, sadece başla."],
 "Hız problemleri": ["Hız sorusunda önce şekil çiz: iki araç, yol, yön.", "Karşılaşma mı, yetişme mi?", "Karşılaşmada hızlar toplanır, yetişmede çıkarılır."],
 "İlk kez yükseldim": ["Tebrikler! Bu fark tesadüf değil.", "Ne değişti sence?", "Ne değiştiyse onu koruyacağız. Bu hafta aynı düzen."],
 "Kıyafet ve sınav": ["Sınav günü rahat, katman katman kıyafet.", "Salon sıcak ya da soğuk olabilir.", "Kimlik, su, kalem bir gece önce çantada."],
 "Kaygı kötüdür": ["Biraz kaygı dikkati açar.", "Çok kaygı ise dikkati kapatır.", "Kaygıyı yok etmeye çalışma, nefesle yönet."],
 "Deneme notları": ["Denemeden sonra üç cümle yaz.", "Ne iyi gitti, ne kötü gitti, ne değişecek?", "Bir ay sonra bu notlar sana yol gösterir."],
 "Sessiz akşam": ["Bu akşam hiçbir şey planlama.", "Dinlen, sevdiğin bir şeyi yap.", "Yarın taze başlarız."],
 "Kopya plan": ["Başkasının planı onun hayatına göre yazıldı.", "Onun uyku saati, okul saati, hızı senin değil.", "Kendi planını kendi gününe göre kur."],
 "Nüfus piramitleri": ["Piramidin tabanı genişse genç nüfus çok.", "Tepesi genişse yaşlı nüfus artıyor.", "Şekle bakınca ülkenin geleceği okunur."],
 "Kaç saat uyumalıyım": ["4 saat uykuyla çalışmak ertesi günü çöpe atar.", "Ama zaman yetmiyor.", "7–8 saat uyu. Uyanık geçen her saat daha verimli olur."],
 "Anne–baba ortak dil": ["Anne bir şey, baba başka şey derse çocuk kaybolur.", "Önce ikiniz aynı noktada buluşun.", "Sonra çocuğunuzla konuşun."],
 "Deneme sonrası dinlenmek israf": ["Deneme sonrası hemen dinlenmek israf değil.", "Ama analizi atlamak israf.", "Bir saat dinlen, sonra 20 dakika analiz."],
 "Deneme bağımlılığı": ["Her gün deneme çözüp analiz etmemek, hiç çözmemek gibi.", "Deneme ölçer, analiz geliştirir.", "Haftada bir deneme, bir analiz."],
 "Kaybettiğin günler": ["Kötü geçen günler kayıp değil.", "Her birinden bir ders çıkardın.", "Kaybettiğin gün yok, öğrendiğin gün var."],
 "Günlük minimum": ["Kötü günde de bir minimum olsun: 20 soru.", "Minimum, zinciri koparmaz.", "Zincir kopmazsa ertesi gün kolay başlarsın."],
 "Optik": ["Aynada görüntü sorusunda en az iki ışın çiz.", "Birini paralel gönder, odaktan geçir.", "İki ışının kesiştiği yer görüntüdür."],
 "Soru atlamak": ["Takıldığın soruya 5 dakika vermek, 3 kolay soruyu götürür.", "Ama bırakınca içim rahat etmiyor.", "Soruya işaret koy, sona dön. İşaret, geri döneceğinin sözü."],
 "Yerleştirme sonuçları": ["Yerleştirme sonuçları açıklandı.", "Kazandıysan tebrikler, yeni bir yol başlıyor.", "Kazanamadıysan da yol bitmedi. Bir sonraki adımı birlikte kurarız."],
 "Plan esnek olmamalı": ["Hiç esnemeyen plan ilk sürprizde kırılır.", "Planına boş bir saat koy.", "Beklenmedik bir şey olunca o saat kurtarır."],
 "Kolaydan zora": ["Denemede sırayla gitmek zorunda değilsin.", "Önce kolay soruları topla.", "Zor sorulara kalan zamanı ayır."],
 "Kendine mektup": ["Gelecek yılın haziranında okuyacağın bir cümle yaz.", "Şu anki sen ona ne demek istiyor?", "Zarfı kapat, bir kitabın arasına koy."],
 "Zafer Bayramı": ["30 Ağustos Zafer Bayramı kutlu olsun.", "Bağımsızlığımızı kazandıran bütün kahramanlarımızı saygıyla anıyoruz.", "Bugün bayram."],
 "Organik adlandırma": ["Önce en uzun karbon zincirini bul.", "Dallanmaları en küçük numarayla işaretle.", "Gerisi ek ve sıralama."],
 # Eylül
 "Aynı hata": ["Aynı hatayı tekrar yapmak, hatanın bir alışkanlık olduğunu gösterir.", "Hep işlem hatası yapıyorum.", "Her soruda son işlemi bir kez kontrol et. İki haftada alışkanlık değişir."],
 "Sosyal medya": ["Bazı ‘motivasyon’ hesapları sürekli kıyas yaptırır.", "Çocuk kendini yetersiz hisseder.", "Birlikte takip listesine bakın. Neler ona iyi geliyor?"],
 "Sadece çalışınca olur": ["Çok çalışmak yetmez, doğru çalışmak gerekir.", "Yanlış yöntemle 10 saat, doğru yöntemle 5 saatten azdır.", "Önce yöntemi düzelt."],
 "Deneme yorgunluğu": ["Denemeden sonra başın ağrıyorsa su içtin mi?", "Uzun süre odaklanmak bedeni yorar.", "Deneme günü bol su, hafif yemek."],
 "Yeni başlangıç": ["Her pazartesiyi yeni başlangıç yapmak yorar.", "Devam etmek daha kolay.", "Kaldığın yerden, küçük bir adımla."],
 "Haftanın ölçüsü": ["Pazar akşamı iki soru sor.", "Kaç iş vardı, kaçı bitti?", "Oran sana bir sonraki haftanın planını söyler."],
 "Ekoloji": ["Besin zincirinde her basamakta enerji azalır.", "Ama zehirli maddeler birikir ve artar.", "Zincirin tepesindeki canlı en çok etkilenir."],
 "Deneme bitmeden sıkılıyorum": ["Dikkat süresi antrenmanla uzar.", "Ama ortasında hep kopuyorum.", "Önce yarım deneme çöz, sonra dörtte üç, sonra tam. Üç haftada dikkat uzar."],
 "Kaygılı veli": ["Sizin kaygınız çocuğunuza da geçebilir.", "Soruları azaltmak, sessizliği artırmak işe yarar.", "Siz sakin olunca o da sakinleşir."],
 "Gürültü alışılır": ["Gürültüye alıştığını sanırsın.", "Ama dikkat her seste bir parça kaybolur.", "Sessiz bir saat ya da kulaklık fark yaratır."],
 "Tahmin stratejisi": ["Hiç fikrin yoksa boş bırak.", "İki şıkka indirdiysen işaretle.", "Dört yanlış bir doğruyu götürür. Hesap bu."],
 "Kontrol edebildiklerin": ["Sorunun zorluğunu kontrol edemezsin.", "Bugün kaç soru çözeceğini, kaçta yatacağını kontrol edebilirsin.", "Kontrol edebildiğine odaklan."],
 "Yeni ders yılı": ["Yeni ders yılı başladı. YKS 2028 bugün başlıyor.", "İlk hafta plan küçük, ritim önemli.", "Her gün aynı saatte masaya otur."],
 "Trigonometri": ["Birim çemberi ezberleme, her seferinde çiz.", "Açıyı çiz, x ve y'yi oku.", "Kosinüs x, sinüs y. Gerisi çizimde."],
 "Ödül": ["Küçük ödüller motivasyonu besler.", "Şımarık olmaz mıyım?", "Emeğe verilen ödül şımartmaz. Haftalık hedef bitince sevdiğin bir şey yap."],
 "Güven": ["Çocuğunuz kötü netini size söyleyebiliyor mu?", "Söyleyebiliyorsa aranızda güven var.", "O güveni korumak için ilk tepkiniz sakin olsun."],
 "Kitap okumak zaman kaybı": ["Kitap okumak paragrafın en iyi antrenmanı.", "Günde 20 sayfa, bir ayda bir kitap.", "Okuma hızın da anlama gücün de artar."],
 "Deneme sonrası uyku": ["Deneme günü beyin çok çalışır.", "O gece erken yat.", "Uyku, denemede öğrendiklerini kaydeder."],
 # Yedek konular (takvim sınav tarihine göre kayarsa kullanılabilir)
 "Yeni ay, sade plan": ["Ay başında planı büyütme.", "Geçen aydan kalanları temizle.", "Sade bir planla yeni aya başla."],
 "Deneme sonrası plan": ["Denemede çıkan üç eksik, bu haftanın planı.", "Her eksiğe bir gün ver.", "Hafta sonu yeni denemede farkı gör."],
 "Plan çizelgesi": ["Haftayı bir kâğıda sığdır.", "Sığmıyorsa plan fazla.", "Kâğıda sığan plan bitirilir."],
 "Tek sayfa hafta": ["Bu hafta tek sayfada: 5 gün, 3 iş, 1 deneme.", "Her iş için bir gün ve saat.", "Pazar akşamı sayfaya bak, işaretle."],
 "Ritmi koru": ["Motivasyon gelir gider.", "Ritim ise her gün aynı saatte başlamaktır.", "Ritmi koruyan, motivasyonu beklemez."],
 "Basınç": ["Basınç sorusunda ilk soru: katı mı, sıvı mı, gaz mı?", "Katıda kuvvet ve yüzey, sıvıda derinlik ve yoğunluk.", "Gazda kapalı kap ve sıcaklık."],
 "Yazım kuralları": ["‘de’ ayrı mı bitişik mi?", "Cümleden çıkar: anlam bozulmuyorsa ayrı yazılır.", "Bozuluyorsa bitişik."],
 "Çemberde açılar": ["Çevre açı, aynı yayı gören merkez açının yarısıdır.", "Önce yayı bul.", "Sonra hangi açının o yayı gördüğüne bak."],
 "Osmanlı dönemleri": ["Osmanlı'yı tek parça çalışma.", "Kuruluş, yükseliş, duraklama, gerileme, dağılma.", "Her dönemin bir tablosunu kur."],
 "Kıskanmak": ["Arkadaşının başarısına sevinememek çok insani.", "Kendimi kötü hissettim.", "Kıskançlık neyi istediğini gösterir. Onu hedefe çevirelim."],
 "Pes etmek üzere": ["Bunu yazdığın için teşekkür ederim. Bıraksan fark edilirdi, sen önemlisin.", "Çok yoruldum.", "Planı yarıya indiriyoruz. Bunu güvendiğin biriyle de konuşmanı istiyorum."],
 "Sonuç günü": ["Sonuç açıklandığında önce sarılın.", "Puana sonra bakılır.", "Çocuğunuz o anda sonuçtan çok sizin yüzünüze bakar."],
 "Çalışma masası": ["İyi bir masa ve iyi bir ışık en ucuz yatırım.", "Loş ışık gözü yorar, dikkat düşer.", "Masada yalnızca o günün kitapları dursun."],
 "Mola hakkı": ["Mola veren çocuk tembel değil.", "Beyin 45–50 dakikada bir dinlenmek ister.", "Molaya kızmak yerine süresini birlikte belirleyin."],
 "Kopya plan işe yarar": ["Birincinin planı onun hayatına göre.", "Senin uykun, okulun, hızın farklı.", "Kendi planını kendi gününe göre kur."],
 "Hızlı okuma kursu": ["Hızlı okumak değil, doğru okumak kazandırır.", "Paragrafta hız, anlamaktan gelir.", "Her gün paragraf çözen hem hızlanır hem anlar."],
 "Soru sayısı yeter": ["Kaç soru çözdüğün kadar kaç yanlışın geri döndüğü önemli.", "Yanlışına bakmadan 200 soru, bakarak 100 sorudan azdır.", "Her gün yanlışlara 15 dakika."],
 "Sıralama kaygısı": ["Deneme sıralaman değişir.", "Katılım ve zorluk her seferinde farklı.", "Sen netine odaklan, sıralama onu takip eder."],
 "Aileyle akşam": ["Bu akşam ailenle yemek ye.", "Konu YKS olmasın.", "Bir akşam dinlenmek haftayı kurtarır."],
 "AYT günü": ["Bugün son oturum.", "Dün ne olduysa oldu, bugün yeni bir sınav.", "Kolay sorularla başla. Bittiğinde bu yıl bitti."],
 "Babalar Günü": ["Sınav yılının sessiz destekçileri: babalar.", "Servis, bekleyiş, akşam sorulan tek soru.", "Babalar Günü kutlu olsun."],
})
