"""Videoların gövdesi: konu başlığı -> 3 kısa satır (her biri ~3 sn ekranda).
Başlığa bağlı tutulur, tarihe değil: takvim kayarsa gövde konusuyla gider.
'Aynı Hafta' serisinde satırlar sırayla koç / öğrenci / koç mesajıdır.
Gövdesi yazılmamış gün üretilmez; iş akışı uyarı verip atlar."""

GOVDE = {
 # Özel günler
 "Dünya Ruh Sağlığı Günü": ["Kalp çarpıntısı, uykusuzluk, mide ağrısı: kaygı böyle konuşur.", "Güvendiğin bir yetişkine anlatmak ilk adım.", "Uzun sürüyorsa okul rehber öğretmeni ya da bir uzman."],
 "İlk deneme bir harita": ["Netin düşük çıkabilir. Olması gereken bu.", "Hangi derste kaç boş var? Haritan o.", "Bir sonraki denemeye tek hedef: +2 net."],
 # Pazar Akşamı
 "Pazar akşamı ağırlığı": ["Pazar akşamı herkesin göğsüne biraz ağırlık çöker.", "Yarının ilk işini şimdi yaz. Sadece ilkini.", "Sonra telefonu bırak, erken uyu."],
 "Haftayı kapat": ["Bu haftanın tek iyi şeyini yaz.", "Bir soruyu ilk kez yapmak da sayılır.", "Kötüleri değil, iyi olanı hatırla. Yarın ona eklersin."],
 "Mevsim değişimi": ["Hava değişince uyku ve enerji de değişir.", "Birkaç gün yavaş hissetmen normal.", "Planı küçült, ritmi koru. Bir haftada alışırsın."],
 "Kendine koç ol": ["Kötü bir günde kendine ne diyorsun?", "Aynı şeyi bir arkadaşına söyler miydin?", "Kendine onunla konuştuğun gibi konuş."],
 # Haftanın Planı
 "Haftayı üç işle başlat": ["Pazartesi 20 iş yazınca cuma 5'i biter.", "Bu hafta sadece 3 iş seç. Hepsine gün ve saat ver.", "Üçü de biterse, dördüncüyü o zaman ekle."],
 "Plan kâğıtta değil, takvimde": ["‘Matematik çalışacağım’ bir niyet.", "‘Salı 19:00, 40 problem’ bir plan.", "Her işe gün ve saat ver. Plan o zaman çalışır."],
 "Okul yoğun haftası": ["Yazılı haftası geldi. Önce yazılılar.", "YKS için her gün sadece 30 dakika: paragraf ve problem.", "Yazılılar bitince tam plana dön. Hiçbir şey kaybolmadı."],
 "Pazartesi sendromu": ["Pazartesi ağır geliyorsa, pazar akşamı plan yoktur.", "Pazar akşamı 10 dakika: haftanın 3 işi.", "Pazartesi sabahı düşünmezsin, başlarsın."],
 # Ders Taktiği
 "Paragrafta önce soru kökü": ["Önce soru kökünü oku: ne soruluyor?", "Sonra paragrafı o gözle oku.", "Aradığını bilerek okuyan daha hızlı bulur."],
 "Problemlerde tabloyu çiz": ["Kişiler satıra, zamanlar sütuna.", "Bugün, x yıl önce, y yıl sonra: üç sütun.", "Tablo dolunca denklem kendini yazar."],
 "Açıyı çizime yaz": ["Soruda verilen her açıyı şeklin üstüne yaz.", "Sonra üçgenlerin iç açılarını tamamla.", "Çoğu zaman aradığın açı kendiliğinden çıkar."],
 "Birimle kontrol et": ["Cevabın birimi ne olmalı? Önce onu yaz.", "Hız m/s ise, işlemin sonunda m/s çıkmalı.", "Birim tutmuyorsa formülü yanlış kurmuşsundur."],
 # Aynı Hafta (koç / öğrenci / koç)
 "Mezun yılı": ["Geçen yıl nerede takıldın, biliyor musun?", "Deneme stresi ve düzensizlik sanırım.", "O zaman bu yılın planı ikisine göre. Aynı yıl değil bu."],
 "Yeni başlıyorum": ["Erken değil. En rahat yıl şu an.", "Ne kadar çalışayım peki?", "Günde 1 saat yeter. Ama her gün. Önce TYT temeli."],
 "Okul yetişmiyor": ["Yazılı haftası YKS'yi durdurmaz, küçültür.", "Her gün ne kadar?", "30 dakika paragraf ve problem. Yazılılar bitince tam plan."],
 "Dün hiç çalışmadım": ["Hayır. İki katı yaparsan yarın da yorgun olursun.", "Peki ne yapayım?", "Bugünün planı ne ise o. Dün geçti, bugün sayılır."],
 # Veli Köşesi
 "LGS velisi": ["1. Her denemeden sonra sonuç sorgusu.", "2. Kardeşle, kuzenle kıyaslamak.", "3. Hafta sonunu tamamen derse ayırmak."],
 "Mezun öğrenci": ["Mezun yılında en büyük risk yalnızlık ve düzensizlik.", "Sabah kalkış saati sabit olsun, gün bir yapıya otursun.", "Haftada bir gün dışarı çıkmak ceza değil, bakım."],
 "Yazılı haftası": ["Yazılı haftasında önce okul.", "YKS'ye her gün kısa bir parça: 30 dakika.", "Yazılı notları OBP'ye girer. İkisi rakip değil."],
 "Kaç soru çözdün diye sormayın": ["‘Kaç soru?’ sorusu bir sınav gibi gelir.", "Onun yerine: ‘Bugün en zor ne vardı?’", "Cevap sorun anlatır. Soru sayısı anlatmaz."],
 # Doğru Bilinen Yanlışlar (gerçek)
 "11. sınıf erken": ["11. sınıf, konuları acele etmeden oturtacağın yıl.", "Günde 1 saat TYT temeli, 12. sınıfta sana aylar kazandırır.", "Erken başlayan yavaş gidebilir. Geç başlayan koşmak zorunda."],
 "Son sınıfta her şey biter": ["Son sınıf sıfırdan başlama yılı değil.", "11. sınıfta ne attıysan onun üstüne kurarsın.", "Hiçbir şey atmadıysan da geç değil: plan küçük, düzen sıkı."],
 "Çok saat = çok net": ["12 saat masada oturmak, 12 saat çalışmak değil.", "Odaklı 5 saat, dağınık 12 saati geçer.", "Saat değil, çözülen ve dönülen soru sayılır."],
 "Deneme her gün çözülür": ["Her gün deneme çözen analize vakit bulamaz.", "Eylül–mart haftada 1, nisandan sonra 2.", "Deneme ölçer. Asıl artış analizden gelir."],
 # Deneme Günü
 "İlk deneme": ["İlk denemenin neti seni tanımlamaz.", "Boş bıraktıkların konu eksiğin, yanlışların dikkat eksiğin.", "İkisini ayrı listele. Pazartesinin planı hazır."],
 "Deneme sabahı rutini": ["Deneme sabahı yeni bir şey deneme.", "Her zamanki kahvaltı, su, aynı kalem.", "Sınav sabahı da böyle olacak. Şimdiden alış."],
}

# ── 17 Ekim – 31 Aralık 2026 ─────────────────────────────────────
GOVDE.update({
 # Ekim
 "Soru sırası stratejisi": ["Her denemede başka sırayla başlamak, her seferinde yeniden alışmak demek.", "Bir sıra seç: Türkçe, sosyal, matematik, fen gibi.", "Beş deneme aynı sırayla git. Sonra karar ver."],
 "Yetmiyorum hissi": ["‘Yetmiyorum’ bir düşünce. Ölçüm değil.", "Ölçüm şu: geçen ay kaç net, bu ay kaç net?", "Çizgi yukarı gidiyorsa, yetiyorsun."],
 "En zor dersi sabaha koy": ["Günün ilk saatinde irade en taze.", "En çok ertelediğin dersi o saate yaz.", "Kolay dersleri akşama bırak. Yorgunken de yapılır."],
 "Mol köprüsü": ["Gram mı verdi? Mole çevir.", "Tanecik mi, hacim mi soruyor? Molden ona geç.", "Her soruda aynı köprü: veri → mol → sorulan."],
 "Denemede düştüm": ["Hayır. Deneme zorlaştı mı, sen mi yoruldun, önce ona bakalım.", "Deneme zordu ama ben de dağınıktım.", "O zaman bu hafta 3 dikkat hatanı yazalım. Net geri gelir."],
 "Deneme sonucu geldiğinde": ["İlk cümle puan olmasın.", "‘Nasıl geçti, sen nasılsın?’ yeter.", "Analiz ertesi gün, çocuk hazır olduğunda."],
 "Müzikle çalışılmaz": ["Sözlü müzik paragrafta dikkati böler.", "Sözsüz, tanıdık müzik tekrar ve soru çözümünde sorun olmayabilir.", "Deneme günü müziksiz: sınavda da müzik yok."],
 "İlk tur ikinci tur": ["İlk tur: bildiğin, hızlı gördüğün sorular.", "Takıldığın soruya işaret koy, geç.", "İkinci turda kalan süreyi işaretlilere harca."],
 "Yarın yeni hafta": ["Geçen hafta ne olduysa oldu.", "Yarın kaldığın konudan, kaldığın sayfadan devam.", "Sıfırdan başlamak her hafta yorar. Devam etmek yormaz."],
 "25 dakikalık blok": ["25 dakika çalış, 5 dakika kalk.", "Dört blok bitince 20 dakika uzun mola.", "Saat ölçme, blok say: bugün kaç blok?"],
 "Şemayla çalış": ["Bir sayfa okumak yerine bir şema çiz.", "Mitozu çiz, sonra kitabı kapatıp yeniden çiz.", "Çizemediğin yer, bilmediğin yerdir."],
 "Arkadaşım benden iyi": ["Onun kaç saat çalıştığını gerçekten biliyor musun?", "Bilmiyorum, öyle anlatıyor.", "O zaman kendi grafiğine bak. Kıyas, tek kişiyle: geçen ayki sen."],
 "Cumhuriyet Bayramı": ["Bugün ders değil, bayram.", "Bu ülkenin okullarında okuyabilmek de onun eseri.", "Yarın kaldığın yerden devam."],
 "Gece çalışmak verimli": ["Gece sessiz olduğu için verimli gelir.", "Ama uyku bölünürse ertesi gün iki saat kaybedersin.", "Sınav sabah 10.15'te. Beynini sabaha alıştır."],
 "Deneme analizi 20 dakika": ["Yanlışları ikiye ayır: bilmedim, dikkat etmedim.", "Bilmediklerin konu listesi, dikkat hataların alışkanlık listesi.", "Her listeden en çok tekrar eden 3 tane: haftanın planı."],
 # Kasım
 "Işık ve ruh hali": ["Hava erken kararınca beden uykuya hazırlanır.", "Masaya sıcak ve güçlü bir lamba koy.", "Gündüz 20 dakika dışarı çık. Işık da çalışmanın parçası."],
 "Tatil sonrası dönüş": ["Tatil dönüşü ilk hafta tam hız yorar.", "Planın yarısıyla başla, çarşamba tam plana geç.", "Önce ritim, sonra yük."],
 "Zaman çizelgesi": ["Kâğıda bir çizgi çiz: yüzyıllar.", "Her olayı çizgide yerine koy.", "Soru ‘önce hangisi’ derse, çizgi cevabı verir."],
 "Ara tatil bitti": ["Yarısı iyi bir oran. Hiç yapmamaktan iyi.", "Ama kötü hissediyorum.", "Hangi yarıyı yaptığına bak. Kalanı önümüzdeki iki haftaya dağıtalım."],
 "Ara tatil": ["İlk 2–3 gün gerçek tatil olsun.", "Sonra her gün birkaç saatlik düzenli tekrar.", "Tatil bitince çocuk yorgun değil, hazır dönsün."],
 "Kış tembel yapar": ["Kışın yorgunluk karanlıktan gelir.", "Işıklı oda, gün içinde dışarıda 20 dakika.", "Yorgunluk tembellik değil. Ona göre plan kurulur."],
 "Yanlış defteri": ["Her denemeden sadece 5 yanlış seç.", "Soruyu yapıştır, doğru çözümü kendi cümlenle yaz.", "Cuma akşamı defteri baştan oku. Hepsi bu."],
 "Kaygıyla yaşamak": ["Sınav yaklaştıkça kaygı gelecek.", "Onu kovmaya çalışma, adını koy: ‘şu an kaygılıyım.’", "Sonra küçük bir iş yap. İş kaygıyı küçültür."],
 "Kış saatleri": ["Hava 17:30'da kararıyor.", "Okuldan dönünce ilk iş, ışık varken en zor ders.", "Karanlık saatlere tekrar ve kolay soru."],
 "10 Kasım": ["Saat 09:05.", "Bir dakikalık saygı duruşu.", "Gençliğe emanet ettiği yolda, çalışarak."],
 "Kış karanlığı": ["Çok normal. Karanlık bedeni yavaşlatır.", "Ne yapayım o zaman?", "Işık varken zor ders, karanlıkta tekrar. Odanı aydınlat."],
 "Kıyaslama": ["Kıyas bir çocuğa ‘yetmiyorsun’ diye duyulur.", "Onun yerine geçen aya göre konuşun.", "‘Geçen ay 42, şimdi 46. Nasıl yaptın?’"],
 "Ara tatil planı": ["İlk 3 gün dinlen: uyku, arkadaş, hareket.", "Sonraki 6 gün: her gün 4 blok tekrar ve bir deneme.", "Tatilin sonunda eksik listesi kısalmış olsun."],
 "Boş bırakma kararı": ["Hiç fikrin yoksa boş bırak.", "İki şıkka indiysen işaretle.", "4 yanlış 1 doğruyu götürür. Kör tahmin kaybettirir."],
 "Küçük zaferler": ["Büyük hedef uzakta, küçük zaferler bu hafta.", "İlk kez yaptığın bir soru, erken kalktığın bir sabah.", "Bunları bir yere yaz. Kötü günde okursun."],
 "Boş gün planla": ["Hiç boş gün yoksa, beden bir gün kendisi alır.", "Haftada yarım gün tamamen boş olsun.", "Boş gün suçluluk değil, planın parçası."],
 "Harita üstünde çalış": ["Coğrafya sorusu bir yer sorar.", "Konuyu okurken haritada göster: nerede, neden orada?", "Harita aklında kalır, cümle kalmaz."],
 "Uyuyamıyorum": ["Yatmadan önce son bir saat telefon var mı?", "Evet, biraz bakıyorum.", "Bir hafta telefonu 23:00'te başka odaya koy. Sonra konuşalım."],
 "Uyku düzeni": ["Gece uyuyamamak çoğu zaman kaygının işaretidir.", "Kızmak yerine birlikte bir saat belirleyin: telefon 23:00'te salonda.", "Sabah aynı saatte kalkış, akşamı da düzeltir."],
 "Konu anlatımı izlemek çalışmaktır": ["Video izlerken her şey anlaşılır gelir.", "Ama sınav izlediğini değil, çözdüğünü sorar.", "Her 20 dakikalık videodan sonra 20 soru."],
 "Süre yönetimi": ["Bir soruya 2 dakikadan fazla takıldıysan işaretle.", "Geç, sona dön.", "Tek soru için 5 dakika, 3 kolay soruyu götürür."],
 "Mükemmel hafta yok": ["Planın hepsi bitmedi mi?", "Yüzde 70 bittiyse iyi bir haftaydı.", "Mükemmel değil, sürekli olan kazanır."],
 "Plan bozulursa ne olur": ["Misafir gelir, hasta olursun, plan bozulur.", "Bozulan günü telafi etmeye çalışma.", "Ertesi gün planın neredeyse oradan devam et."],
 "Öğretmenler Günü": ["Hepimizin hayatında bir öğretmen var.", "Bir cümlesiyle yön değiştirdiğimiz.", "Bugün ona bir mesaj at. Öğretmenler Günü kutlu olsun."],
 "Matematik korkusu": ["Korku genelde temel eksikten gelir.", "Evet, bazı konular hiç oturmadı.", "O zaman bu hafta en temelden: sayılar ve işlem. Kolay sorudan başlayacağız."],
 "Telefon tartışması": ["Telefonu almak kavga başlatır.", "Birlikte kural koymak işe yarar: ders saatinde başka odada.", "Kuralı siz de uygularsanız daha çok işe yarar."],
 "Zeki olan kazanır": ["Zekâ işe yarar ama tek başına yetmez.", "YKS dokuz ay düzen ister.", "Her gün aynı saatte masaya oturan, zeki ama düzensizi geçer."],
 "Net grafiği": ["Her denemenin netini bir çizgiye yaz.", "Tek düşüş bir şey söylemez.", "Üç denemelik yön söyler: yukarı mı, düz mü?"],
 "Dinlenme hakkı": ["Bugün dinlendin mi? Güzel.", "Dinlenen beyin yarın daha iyi çalışır.", "Suçluluk duyma. Bu da planın parçası."],
 "Soru sayısı mı, saat mi?": ["‘5 saat çalıştım’ ne yaptığını söylemez.", "‘120 soru, 14 yanlış’ söyler.", "Günün sonunda sayıyı yaz. İlerlemeyi sayı gösterir."],
 # Aralık
 "YKS'ye 200 gün": ["200 gün uzun gibi görünür, çabuk geçer.", "Haftada 6 iyi gün, 1 dinlenme.", "Her hafta bir deneme, her deneme bir analiz."],
 "Hastalandım": ["Önce iyileş. Hasta çalışmak iki kat kaybettirir.", "Ama geri kalıyorum.", "İyileşince ilk 2 gün yarım plan. Kaçanı dağıtırız, yığmayız."],
 "Sessiz çalışma alanı": ["Televizyon sesi dikkati sessizce yer.", "Çalışma saatinde evin bir köşesi sessiz olsun.", "Bu bir kural değil, destek."],
 "Kolay konular sona": ["Kolay konular ‘nasılsa yaparım’ diye sona kalır.", "Sonra zaman yetmez, kolay puan kaçar.", "Kolay konuyu erken bitir, cebe koy."],
 "Optik hatası": ["Bir soruyu atladın, sonraki cevaplar bir kaydı.", "Her 10 soruda bir optiği kontrol et.", "Deneme bitmeden son 5 dakikayı optiğe ayır."],
 "Kıyas bırak": ["Bu hafta kimsenin netine bakma.", "Sadece kendi dünkü sayına bak.", "Dünden biraz iyiysen, doğru yoldasın."],
 "Okul sonrası ilk saat": ["Okuldan gelince hemen masaya oturmak zor.", "İlk saat: yemek ve 20 dakika hiçbir şey.", "Sonra masaya. Dinlenmiş beyin daha hızlı başlar."],
 "Yeni nesil soru okuma": ["Uzun metin seni korkutmasın.", "Önce soru cümlesini oku, sorulanın altını çiz.", "Sonra metinde sadece gerekli sayıları topla."],
 "Telefonu bırakamıyorum": ["Telefon masadaysa sen de telefondasın.", "Başka odaya koyunca aklım orada kalıyor.", "İlk 3 gün öyle olur. Dördüncü gün unutursun. Deneyelim."],
 "Ev içi yük": ["Küçük bir sorumluluk çocuğa iyi gelir.", "Masayı kurmak, çöpü atmak: 10 dakika.", "Büyük yükler sınav yılında azalsın, sıfırlanmasın."],
 "Kafein mucizesi": ["Enerji içeceği bir saat uyanık tutar.", "Sonra gece uykunu bozar.", "Uyku bozulunca ertesi gün net düşer."],
 "Deneme sonrası duygu": ["Kötü geçen denemenin ardından hemen analiz yapma.", "Bugün yürü, ye, erken uyu.", "Yarın sabah sakin kafayla yanlışlara bak."],
 "Neden başladın": ["Yorulduğun gün hedef uzak görünür.", "Neden başladığını bir kâğıda yaz.", "Masanın önüne as. Zor günde oku."],
 "Tekrar günü": ["Her hafta yeni konu eklemek, eskiyi unutturur.", "Bu hafta geçen haftanın konularını tekrar et.", "Tekrar edilen konu, sınavda hatırlanır."],
 "Dil bilgisinde eleme": ["Emin olamadığın soruda doğru şıkkı arama.", "Kesin yanlış olanları tek tek ele.", "İki şık kalırsa kurala dön, karar ver."],
 "Ailem baskı yapıyor": ["Annen de kaygılı. Soru sayısı ona güven veriyor.", "Ama her akşam hesap veriyor gibiyim.", "Haftada bir gün sen anlat: ne yaptın, ne zorladı. Soru azalır."],
 "Motivasyon konuşması": ["Uzun nasihat dinlenmez.", "Tek cümle akılda kalır: ‘Yanındayım.’", "Sonrası sessizlik. Çocuk isterse konuşur."],
 "Özet çıkarmak şart": ["Güzel özet yazmak saatler alır.", "Çoğu zaman o saatlerde soru çözülebilirdi.", "Sadece ezber gereken konulara kısa not, gerisine soru."],
 "Evde deneme koşulları": ["Evde deneme, sınavın provasıdır.", "Telefon başka odada, saat görünür yerde, sınav saatinde başla.", "Masada su ve iki kalem. Başka hiçbir şey."],
 "Yalnızlık": ["Bu yıl arkadaşlarla daha az görüşüyorsun.", "Yalnız hissetmek normal.", "Haftada bir kez birini ara ya da buluş. Ders konuşmadan."],
 "Yılın en uzun gecesi": ["Bugün en kısa gün, en uzun gece.", "Yarından itibaren her gün biraz daha ışık.", "En karanlık yeri geçtin."],
 "Sayı basamakları": ["ab iki basamaklı sayı ise 10a + b.", "Harfleri hemen bu şekle çevir.", "Gerisi basit bir denklem."],
 "Hedefimi değiştirsem mi": ["Şu an netin kaç, hedefin için kaç lazım?", "Arada 30 net var.", "Altı ayda 30 net zor ama olur. Karar mart denemelerinden sonra."],
 "Dershane kararı": ["Dershane konu anlatır ve deneme yaptırır.", "Özel ders tek bir eksiği kapatır.", "Koç planı kurar ve takip eder. İhtiyaca göre seçilir."],
 "Boş bırakmak kaybettirir": ["4 yanlış 1 doğruyu götürür.", "Tamamen tahmin, ortalamada kaybettirir.", "İki şıkka indiysen işaretle; hiç fikrin yoksa boş bırak."],
 "Türkiye geneli deneme": ["Türkiye geneli deneme sıralaman bir fotoğraf.", "Katılanlar ve zorluk her seferinde değişir.", "Asıl bakacağın: kendi netinin yönü."],
 "Beden de çalışır": ["Masada 6 saat oturan beden yorulur.", "Günde 20 dakika yürüyüş dikkati açar.", "Hareket de çalışmanın parçası."],
 "Telefon başka odada": ["Telefon masadaysa bildirim beklersin.", "Başka odaya koy, sessize al.", "Mola saatinde bakarsın. Mola daha tatlı olur."],
 "Türevde grafik oku": ["Grafik verildiğinde önce türevin işaretine bak.", "Türev pozitifse artan, negatifse azalan.", "İşaret değiştiği yer ekstremum."],
 "Konuyu anlamadım": ["Üç kere izlemek yerine bir kere çöz.", "Hangi adımda takılıyorsun?", "O adımın 5 kolay sorusunu çözelim. Anlamak çözerken gelir."],
 "Yılbaşı gecesi": ["Bu gece ders yok.", "Aileyle, arkadaşlarla, dinlenerek.", "Yarın 2027. Sınav yılı sakin başlasın."],
})

# ── 1 Ocak – 31 Mart 2027 ────────────────────────────────────────
GOVDE.update({
 # Ocak: karne, yarıyıl
 "2027: sınav yılı": ["Yeni yıl kararı genelde ocak ortasında biter.", "Yeni plan yapma. Eylülden beri işleyen planı sakinleştir.", "Tek değişiklik: her hafta bir deneme, bir analiz."],
 "Dönem sonu denemesi": ["Bu deneme, dönemin karnesi.", "Eylüldeki ilk denemenle yan yana koy.", "Hangi derste en çok yol aldın? Oradan güç al."],
 "Sınav senin değerin değil": ["Bir sınavdaki netin bir günü ölçer.", "Senin emeğini, sabrını, iyiliğini ölçmez.", "Sonuç ne olursa olsun, sen o sonuçtan büyüksün."],
 "Haftalık tek hedef": ["Bu hafta her şeyi düzeltmeye çalışma.", "Tek cümle yaz: ‘Bu hafta paragrafta süreyi 2 dakika kısaltacağım.’", "Pazar akşamı bu cümleye bak."],
 "Dönem–sanatçı eşleşmesi": ["Bir tablo çiz: dönem, sanatçı, eser, özellik.", "Her gün beş satır ekle.", "Soru ‘hangisi bu döneme ait değil’ derse, tablo cevap verir."],
 "Motivasyonum yok": ["Motivasyonu bekleme. Masaya otur, 10 kolay soru çöz.", "10 soruda ne değişir?", "Başlamak motivasyon getirir. Beklemek getirmez."],
 "Karne haftası": ["Önce çocuğunuzun yüzüne bakın, sonra nota.", "Hangi derste yükseldi? Oradan başlayın.", "Düşük notu yarıyılda birlikte ele alırsınız, bu akşam değil."],
 "Motivasyon beklenir": ["Motivasyon bir duygu, gelir gider.", "Düzen bir karar, her gün aynı saatte masaya oturmak.", "Düzenli olanın motivasyonu çalışırken gelir."],
 "Branş denemesi": ["Genel deneme her şeyi ölçer, yorar.", "Hafta içi sadece bir ders: 20 dakikalık branş denemesi.", "Hafta sonu genel deneme. Denge bu."],
 "Gelecek kaygısı": ["Haziranı, üniversiteyi, meslek seçimini düşünmek ağır gelir.", "Onları şimdi çözmek zorunda değilsin.", "Bugünün işini bitir. Gelecek bugünlerden yapılır."],
 "Zayıf konu listesi": ["‘Matematik kötü’ bir liste değil.", "‘Üslü sayılar, problemler, olasılık’ bir liste.", "Adını koyduğun eksik, bu hafta çalışılır."],
 "Serbest cisim diyagramı": ["Cismi bir nokta gibi çiz.", "Üstüne etki eden her kuvveti ok olarak çiz: ağırlık, tepki, sürtünme.", "Oklar hazırsa formül kendiliğinden gelir."],
 "Plan çok ağır": ["Planın yüzde kaçını bitirebiliyorsun?", "Yarısını belki.", "Planı yarıya indiriyoruz. Bitmiş küçük plan, bitmemiş büyük plandan iyidir."],
 "Sınav kaygısı belirtileri": ["Sınav yaklaşınca mide ağrısı, uykusuzluk, öfke artabilir.", "Bunlar tembellik ya da şımarıklık değil, kaygının belirtisi olabilir.", "Uzun sürüyorsa okulun rehber öğretmeniyle görüşün."],
 "Tek kaynak yetmez": ["Beş kaynağın ilk 50 sayfası, bir kaynağın 250 sayfası değildir.", "Bir kaynağı baştan sona bitir.", "Sonra ikincisine geç. Bitmek de öğretir."],
 "Dikkat dağılınca": ["Denemenin ortasında dikkat dağılır. Herkeste olur.", "Kalemi bırak, gözünü kapat, 3 derin nefes.", "30 saniye kaybedip 10 dakika kazanırsın."],
 "Ailene teşekkür": ["Sınav yılında evde herkes biraz senin için yaşıyor.", "Sessizlik, yemek, bekleyiş.", "Bu hafta birine teşekkür et. Tek cümle yeter."],
 "Çalışma saatini sabitle": ["Her gün başka saatte başlamak her gün yeniden karar vermek demek.", "Bir saat seç: mesela 19:00.", "Üç hafta sonra o saat geldiğinde beden kendiliğinden masaya gider."],
 "Periyodik tabloda yön": ["Sağa gittikçe elektronegatiflik artar.", "Yukarı çıktıkça da artar.", "En elektronegatif: sağ üst köşe, flor."],
 "YKS'ye 150 gün": ["150 gün: 21 hafta.", "Her hafta bir deneme, bir analiz, bir tekrar günü.", "Tempo sabit. Panik yok."],
 "Ödül ve ceza": ["Büyük ödül çocuğu kısa süre heyecanlandırır.", "Sonra kaybetme korkusu başlar, kaygı artar.", "Küçük ve sık takdir daha çok işe yarar: ‘Bu hafta çok düzenliydin.’"],
 "Karne günü": ["Bugün önce sarılın.", "Sonra birlikte bakın: hangi ders yükseldi?", "Düşük notları yarıyıl tatilinde sakin bir planla konuşun."],
 "Kolay soruyu kaçırmak": ["Zor soruyu yapamamak normal.", "Kolay soruyu kaçırmak pahalı.", "Bu denemede kaç kolay soru kaçtı? Onlar en ucuz net."],
 "Uyku borcu": ["Haftanın yorgunluğu uyku borcu olarak birikir.", "Bu gece bir saat erken yat.", "Pazartesi dikkatin fark eder."],
 "Yarıyıl: yılın en değerli 16 günü": ["İlk 3 gün tam dinlenme.", "Sonraki 13 gün: sabah konu, öğlen soru, akşam tekrar.", "Her hafta 2 deneme. Birinci dönemin eksikleri kapansın."],
 "Deney sorularında değişken": ["Deneyde neyi değiştirdiler? Bağımsız değişken.", "Neyi ölçtüler? Bağımlı değişken.", "Neyi aynı tuttular? Kontrol. Üçünü yazınca soru çözülür."],
 "Sınav kaygısı": ["İlk 10 dakika kaygının en yüksek olduğu an.", "Evet, gözüm okuyor ama aklım almıyor.", "İlk 3 dakika sadece kolay soruları işaretle. Beyin ısınınca kaygı düşer."],
 "Beslenme": ["Sabah kahvaltısı dikkatin yakıtı.", "Aç karnına deneme, ilk bir saatten sonra düşer.", "Basit yeter: yumurta, peynir, ekmek, su."],
 "Sabah erken kalkan kazanır": ["Saat 5'te kalkıp öğlen uyuklamak kazandırmaz.", "Her gün aynı saatte kalkmak kazandırır.", "Uykunu değil, düzenini sabitle."],
 "Deneme sıklığı": ["Eylül–ocak: haftada 1 deneme.", "Şubat–nisan: haftada 1 genel, 1 branş.", "Mayıs: haftada 2. Her birinin analizi şart."],
 "Kötü hafta": ["Bu hafta planın yarısı bile olmadı.", "Bir hafta, 40 haftalık yolun küçük bir parçası.", "Yarın küçük bir işle başla. Yeter."],
 # Şubat: ikinci dönem, 6 Şubat, Ramazan, başvuru
 "Yorgunluk haftası": ["Yorgun olduğunu fark etmek iyi bir şey.", "Plan iptal olmaz, yarıya iner.", "Bu hafta uyku ve tekrar. Yeni konu yok."],
 "Tuzak kelimeler": ["‘Yalnızca’, ‘kesinlikle’, ‘her zaman’ biyolojide çoğu zaman yanlıştır.", "Canlılarda istisna çoktur.", "Bu kelimeyi gördüysen şıkkı iki kez oku."],
 "Kitaplar bitmiyor": ["Beş kitabın hiçbiri bitmezse eksikler hep aynı yerde kalır.", "Hangisi en çok işine yarıyor?", "O kalsın, diğerleri rafa. Önce bir kitap bitsin."],
 "Hafta sonu dengesi": ["Pazar günü birkaç saatlik aile gezmesi yasak değil.", "Tersine, beyin dinlenir, hafta daha iyi başlar.", "Tek kural: gezinin saati önceden belli olsun."],
 "Deneme neti = gerçek net": ["Bir denemenin neti o günün fotoğrafı.", "Uyku, zorluk, moral değişir.", "Son üç denemenin ortalaması gerçeğe daha yakın."],
 "6 Şubat": ["6 Şubat 2023.", "Kaybettiğimiz canları rahmetle anıyoruz.", "Yaralarını saran herkese şükranla."],
 "Hedefi küçült": ["Hedef büyük olabilir: tıp, hukuk, mühendislik.", "Ama bugünün adımı küçük olmalı: 40 soru.", "Küçük adımlar birikir, büyük hedefe varır."],
 "İkinci dönem ve Ramazan": ["İkinci dönem başladı, Ramazan da başlıyor.", "Oruçluysan zor dersi sahurdan sonra ya da iftardan bir saat sonra çalış.", "İftardan hemen önce zor soru çözme, tekrar yap."],
 "Anlatım bozukluğu": ["Anlatım bozukluğu sorusunda cümleyi içinden değil sesli oku.", "Kulak tuhaflığı kuraldan önce yakalar.", "Sonra kurala bak: gereksiz kelime mi, yanlış ek mi?"],
 "Paragraf yavaş": ["Kaç dakikada kaç paragraf çözüyorsun, ölçtün mü?", "40 soruya 50 dakika gidiyor.", "Her gün 20 paragraf, süre tutarak. Üç haftada 10 dakika kazanırsın."],
 "YKS başvuru dönemi": ["Başvuru ÖSYM'nin açıkladığı tarihlerde yapılır.", "Kimlik, güncel fotoğraf ve ücret hazır olsun.", "Son güne bırakmayın. Sistem son gün yavaşlar."],
 "Ezber her şeydir": ["Tarih bir hikâye.", "Neden oldu, sonra ne oldu? Bu sırayı bilen tarihi hatırlar.", "Kopuk ezber iki gün sonra uçar."],
 "AYT denemesi": ["AYT, TYT'den uzun ve yorucu.", "Önce en güçlü olduğun testten başla.", "Yanında su ve küçük bir atıştırmalık olsun."],
 "Telefonsuz akşam": ["Bu akşam bir saat telefon başka odada.", "Kitap oku, yürü, ailenle otur.", "Bir saat sonra dön. Kaçırdığın hiçbir şey olmadı."],
 "Deneme haftası planı": ["Deneme olan hafta yeni konu açma.", "Son konuların tekrarı ve soru çözümü yeter.", "Deneme bitince analiz, sonra yeni konu."],
 "Yardımcı çizgi": ["Geometride takıldın mı? Şekle bir şey ekle.", "Bir dikme, bir paralel ya da bir köşegen.", "Çoğu soru bir çizgiyle üçgene dönüşür."],
 "Ezberim uçuyor": ["İki gün sonra unutmak beynin normal hâli.", "O zaman boşuna mı çalışıyorum?", "Hayır: 1 gün, 3 gün, 7 gün sonra kısa tekrar yap. Kalıcı olur."],
 "Öğretmenle iletişim": ["Çocuğunuz uzun süre isteksiz, uykusuz ya da içine kapanıksa.", "Ya da notlarında ani bir düşüş varsa.", "Okulun rehber öğretmeni ilk ve ücretsiz kapıdır."],
 "Koç = öğretmen": ["Öğretmen konuyu anlatır.", "Koç planı kurar, takip eder, tıkandığında yolu değiştirir.", "İkisi birbirinin yerine geçmez, birbirini tamamlar."],
 "Deneme karşılaştırma": ["Arkadaşınla netini kıyaslamak seni yorar.", "Kendi dünkü netinle kıyasla.", "Ondan iyiysen doğru yoldasın."],
 "İyi ki çalıştın": ["Bu hafta yorulduysan, çalıştığın içindir.", "Yorgunluk emeğin izidir.", "Bu akşam dinlen. Hak ettin."],
 "Plan ile program farkı": ["Okulun ders programı sana verilen bir çizelge.", "Senin planın, o programın boşluklarını nasıl kullandığın.", "Programı değiştiremezsin, planı değiştirebilirsin."],
 "Oran orantı": ["a/b = 2/3 ise a = 2k, b = 3k de.", "Bütün bilinmeyenler tek bir k'ye bağlanır.", "Sonra k'yi bul. Oran sorusu bitti."],
 "Kardeşim gürültü": ["Evde sessiz bir saat bulmak zor olabilir.", "Kardeşim akşamları hep oyun oynuyor.", "Ailenle bir saat kararlaştır: 19–21 ev sessiz. Kulaklık da işe yarar."],
 "Ekran süresi": ["Telefonu tamamen yasaklamak gizli kullanımı artırır.", "Birlikte saat koyun: ders saatinde başka odada.", "Akşam bir saat serbest. Kural ikiniz için de geçerli olsun."],
 "Yanlış soruya bakılmaz": ["Yanlış yaptığın soru sana eksiğini gösterir.", "Ona bakmamak, aynı yanlışı sınavda tekrar yapmak demek.", "Her denemeden 5 yanlış: nedenini yaz."],
 "Konu eksiği mi, dikkat mi": ["Yanlışlarını iki sütuna ayır.", "Bilmediğin konular: bu haftanın çalışma listesi.", "Dikkat hataları: soruyu iki kez okuma alışkanlığı."],
 "Pes etmek istemek": ["Bir noktada ‘bıraksam’ diye düşünmek çok normal.", "Bu düşünce geldiğinde karar verme, sadece dinlen.", "Ertesi gün hâlâ aynı düşünüyorsan, biriyle konuş."],
 # Mart: bayram, 100 gün, bahar
 "Sınavdan geriye plan": ["Sınava 16 hafta kaldı.", "Son 4 hafta: sadece deneme ve tekrar.", "Geriye kalan 12 hafta: eksik konular. Takvime yaz."],
 "Neden–sonuç zinciri": ["Tarih sorusu çoğu zaman ‘neden’ ya da ‘sonucu nedir’ diye sorar.", "Her olay için üç kutu çiz: sebep, olay, sonuç.", "Kutular dolunca soru kolaylaşır."],
 "Bayram çalışması": ["Bayramda hiç çalışmasan da dünya yıkılmaz.", "Ama bir hafta hiç dokunmazsam korkuyorum.", "O zaman bayramda her gün 1 saat. Sabah, misafirlerden önce."],
 "Bayram ziyaretleri": ["Bayramda en çok sorulan soru: ‘Kaç net yapıyorsun?’", "Çocuğunuz her seferinde bir sınav gibi hisseder.", "‘Çok çalışıyor, bayramda dinleniyor’ demeniz yeter."],
 "Bayramda çalışılmaz": ["Bayramda üç gün çalışmamak kimseyi geri bırakmaz.", "Asıl risk, bayramdan sonra dönememek.", "Bayram bitince ilk gün, küçük bir planla başla."],
 "Bayram denemesi": ["Uzun tatilin bir gününü deneme günü yap.", "Sınav saatinde başla, sınav gibi çöz.", "Kalan günler dinlenme ve kısa tekrar."],
 "Yavaş ilerleme": ["Netin her hafta artmıyor diye durduğunu sanma.", "Temel oturuyor, artış sonra gelir.", "Yavaş ilerlemek durmaktan iyidir."],
 "Arife ve ara tatil": ["Bayram ve ara tatil birleşti: 9 gün.", "Her gün bir saat kural: sabah, kısa tekrar.", "Bir gün de deneme. Gerisi bayram."],
 "Ramazan Bayramı": ["Bayramınız mübarek olsun.", "Bugün aile, sofra ve dinlenme günü.", "Yarın her gün bir saat kuralı devam."],
 "Son 100 gün paniği": ["Yetişmeyecek diye düşündüğün şey ne?", "Fizik ve geometri daha bitmedi.", "100 günde ikisine birer ay. Kalan zaman tekrar. Yetişir."],
 "YKS'ye 100 gün": ["100 gün kaldı. Yeni konu yavaşlıyor.", "Eksik konulara son 6 hafta, sonra tekrar ve deneme.", "Her gün aynı ritim. Panik değil, tempo."],
 "Uyku kaybıdır": ["Uyku sırasında beyin gün içinde öğrendiklerini kaydeder.", "Az uyuyan öğrenci öğrendiğinin bir kısmını kaybeder.", "7–8 saat uyku, çalışmanın bir parçasıdır."],
 "Deneme sonrası ödül": ["Deneme bitince bir saat tamamen boş.", "Yürü, müzik dinle, bir arkadaşınla konuş.", "Analiz bir saat sonra, taze kafayla."],
 "Kendini affet": ["Bu hafta planladıklarının hepsini yapamadın.", "Kendine kızmak bir sonraki haftayı da bozar.", "Affet, küçük bir planla yeniden başla."],
 "Kırmızı kutular": ["Yapılmayan iş silinmez.", "Ya bir sonraki güne taşınır ya da küçülür.", "Planındaki kırmızı kutuları her pazar akşamı yeniden yerleştir."],
 "Filozof–kavram eşlemesi": ["Kavramı tek başına ezberleme.", "Filozofun ağzından bir cümle kur: ‘Descartes: Düşünüyorum, öyleyse varım.’", "Cümle akılda kalır, kavram onunla gelir."],
 "Dershane mi, evden mi": ["Etüt sana ne kazandırır, önce onu düşün.", "Evde dikkatim dağılıyor.", "O zaman haftada iki gün etüt, diğer günler evde düzen. Deneyip bakarız."],
 "Hedef konuşması": ["Çocuğunuzun hedefi sizin hayaliniz olabilir.", "Kendi seçmediği hedefe çalışmak çok daha zor.", "Önce onu dinleyin: ne okumak istiyor, neden?"],
 "Sosyal hayat bitmeli": ["Bir yıl boyunca arkadaşsız kalmak yalnızlığı artırır.", "Yalnızlık da odağı azaltır.", "Haftada bir kez biriyle buluş. Ders konuşmadan."],
 "Zor deneme": ["Deneme zor geldiyse herkese zor geldi.", "Sıralaman netinden daha doğru bilgi verir.", "Zor denemenin analizi, kolay denemeninkinden çok şey öğretir."],
 "Gün geceyi geçti": ["Bugün gece ve gündüz eşit.", "Yarından itibaren gündüz daha uzun.", "Işık uzuyor. Enerji de onunla artar."],
 "Sabah 20 dakika": ["Okuldan önce 20 dakika paragraf.", "Günün en taze saatinde, en kolay kazanç.", "Bir ayda 400 paragraf eder."],
 "Limitte belirsizlik": ["Limitte 0/0 gördüysen ilk refleks çarpanlara ayırmak.", "Ortak çarpanı sadeleştir.", "Olmuyorsa eşleniğiyle çarp. Çoğu soru bu ikisinden biri."],
 "Hafta sonu kaçtı": ["Utanmana gerek yok. Hafta sonu kaçtı, hafta kaçmadı.", "Ama pazartesi hiç başlayasım yok.", "Bugün sadece planın ilk işini yap. Gerisi kendiliğinden gelir."],
 "Kötü gün": ["Çocuğunuz ‘bugün hiç çalışmadım’ dediyse, bunu söyleyebilmesi güvenin işareti.", "Kızmak bir sonraki sefer saklamasına yol açar.", "‘Yarın ne yapacaksın?’ diye sormanız yeter."],
 "Paragraf yeteneğe bağlı": ["Paragrafta hızlı olanlar doğuştan hızlı değil.", "Her gün paragraf çözen hızlanır.", "Günde 20 paragraf, bir ayda fark eder."],
 "Paragraf süresi": ["Bu denemede paragrafa kaç dakika harcadın?", "Hedef: soru başına bir dakikanın altı.", "Fazlaysa önce soru kökünü okuma alışkanlığını dene."],
 "Plan hazırlığı": ["Yarının ilk işini bu akşam yaz.", "Sabah ‘ne yapsam’ diye düşünmeden başlarsın.", "İlk iş bitince gün kendiliğinden yürür."],
 "Yatmadan 10 dakika": ["Yatmadan önce 10 dakika: bugün yanlış yaptığın 3 soru.", "Doğru çözümü bir kez daha oku.", "Uyku onları senin için kaydeder."],
 "Grafik yorumlama": ["Grafik sorusunda önce eksenleri oku: ne ölçülüyor, birimi ne?", "Sonra çizginin nerede arttığına, nerede azaldığına bak.", "Soruyu grafiğe değil, sorunun sorduğuna göre oku."],
 "Net takıldı": ["Net üç hafta aynı kalıyorsa yöntem değişmeli.", "Hep aynı şekilde çalışıyorum ama.", "Bu hafta konu değil yanlış analizi yapıyoruz. Net oradan açılır."],
})
