-- Kitap kütüphanesi genişlemesi (19 Eylül 2026): 28 → 81 kitap, seviye
-- işaretleri, 18 yeni söz. Sayfa sayıları yaygın Türkçe baskılara göre
-- yaklaşık; süre sayfa × 1,15 dk.

update public.haftalik_kitap set seviye = 'yks' where ad in (
  '1984', 'Sineklerin Tanrısı', 'Bir İdam Mahkûmunun Son Günü', 'İvan İlyiç''in Ölümü',
  'Yeraltından Notlar', 'Anayurt Oteli', 'Bir Bilim Adamının Romanı', 'Denemeler',
  'Bilinmeyen Bir Kadının Mektubu', 'Fareler ve İnsanlar', 'Yaban', 'Sokrates''in Savunması');

insert into public.haftalik_kitap (ad, yazar, yil, sayfa, sure_dk, neden, etiket, emoji, seviye, sira, aktif) values
('Yabancı','Albert Camus','1942',120,140,'Her şeye kayıtsız görünen bir adamın bir yaz günü hayatını değiştiren anı. Kısa, çıplak cümlelerle yazılmış; okurken "ben olsam ne hissederdim" diye sormadan duramıyorsun.','{kisa,dunya_klasigi,felsefe}','☀️','yks',300,true),
('Veba','Albert Camus','1947',290,330,'Salgınla kapanan bir şehirde insanlar sırayla kaçar, pes eder ya da işini yapmaya devam eder. Uzun bir yolu gösterişsiz, her gün biraz yürüyerek bitirmenin romanı.','{orta,dunya_klasigi,felsefe}','🏙️','yks',310,true),
('Dorian Gray''in Portresi','Oscar Wilde','1890',250,290,'Yaşlanmayan bir genç ve onun yerine çürüyen bir tablo. Dışarıya gösterdiğimiz yüzle içimizdekinin arasındaki farkı keskin, esprili bir dille anlatır.','{orta,dunya_klasigi}','🖼️','yks',320,true),
('Frankenstein','Mary Shelley','1818',250,290,'Bilim insanı yarattığı şeyle yüzleşemeyip kaçar. İlk bilimkurgu romanlarından biri; sorumluluk almanın ne demek olduğunu hiç ders vermeden düşündürür.','{orta,dunya_klasigi,bilim}','⚡','ikisi',330,true),
('Dr. Jekyll ile Bay Hyde','Robert Louis Stevenson','1886',90,100,'Saygın bir doktorun içindeki karanlık yarının hikâyesi. Bir akşamda biter, gerilimi son sayfaya kadar düşmez.','{kisa,dunya_klasigi,tek_oturusta}','🧪','ikisi',340,true),
('Palto','Nikolay Gogol','1842',60,70,'Küçük bir memurun tek hayali yeni bir palto. Rus edebiyatının "hepimiz Gogol''un paltosundan çıktık" dediği öykü; bir molada okunur.','{kisa,dunya_klasigi,tek_oturusta,oyku}','🧣','ikisi',350,true),
('Siddhartha','Hermann Hesse','1922',150,170,'Her şeye sahipken arayışa çıkan bir gencin yolculuğu. Başkasının anlattığıyla değil, kendi yaşadığıyla öğrenmenin kitabı.','{kisa,dunya_klasigi,felsefe}','🌊','yks',360,true),
('Demian','Hermann Hesse','1919',170,200,'Bir gencin ailesinin güvenli dünyasından çıkıp kendi yolunu bulmaya çalışması. Kendini arayan her lise öğrencisine tanıdık gelir.','{orta,dunya_klasigi}','🥚','yks',370,true),
('Babalar ve Oğullar','İvan Turgenyev','1862',250,290,'İki kuşak aynı sofrada anlaşamaz. Ailenle tartıştığın konuların 160 yıl önce de konuşulduğunu görmek insanı rahatlatıyor.','{orta,dunya_klasigi}','👥','yks',380,true),
('Kumarbaz','Fyodor Dostoyevski','1866',180,210,'Bir kez daha oynarsa her şeyi düzelteceğine inanan bir adam. Dostoyevski''nin borcunu ödemek için 26 günde yazdığı, en hızlı okunan romanı.','{orta,dunya_klasigi}','🎲','yks',390,true),
('Muhteşem Gatsby','F. Scott Fitzgerald','1925',200,230,'Bütün hayatını bir hedefe kilitleyen bir adamın hikâyesi. Hedefin kendisiyle ona duyduğun hayranlık arasındaki farkı düşündürür.','{orta,dunya_klasigi}','💚','yks',400,true),
('Cesur Yeni Dünya','Aldous Huxley','1932',290,330,'Herkesin mutlu olmaya programlandığı bir gelecek. 1984''ün kardeşi; biri korkuyla, öteki hazla yönetilen iki dünyayı karşılaştırmak için birlikte okunur.','{orta,dunya_klasigi}','🧬','yks',410,true),
('Suç ve Ceza','Fyodor Dostoyevski','1866',700,800,'Bir fikrin peşinden giden bir öğrencinin iç hesaplaşması. Uzun ama sürükleyici; tatilde başlanıp bitirilecek büyük klasik.','{uzun,dunya_klasigi,tatil_icin}','🌉','yks',420,true),
('Martin Eden','Jack London','1909',450,520,'Okulu yarım bırakmış bir denizci, yazar olmak için kendi kendine her şeyi öğrenir. Emeğin, disiplinin ve bedelinin romanı; çalışan her öğrenciye dokunur.','{uzun,dunya_klasigi,tatil_icin}','📚','yks',430,true),
('Beyaz Diş','Jack London','1906',250,290,'Vahşi doğada doğan bir kurt köpeğinin güveni öğrenmesi. Macerası bol, dili yalın; uzun süredir kitap okumayan biri için iyi bir başlangıç.','{orta,dunya_klasigi}','🐺','ikisi',440,true),
('Değirmenimden Mektuplar','Alphonse Daudet','1869',180,210,'Provence''ta bir değirmenden yazılmış kısa öyküler. Her biri on beş dakikalık; yoğun haftada her gün bir tane okunur.','{orta,dunya_klasigi,oyku}','🍃','ikisi',450,true),
('Robinson Crusoe','Daniel Defoe','1719',300,350,'Issız adada tek başına kalan bir adam her gün küçük bir işle hayatını kurar. Plan yapmanın ve sabrın en eski romanı.','{orta,dunya_klasigi}','🏝️','ikisi',460,true),
('Define Adası','Robert Louis Stevenson','1883',250,290,'Bir harita, bir korsan, bir çocuk. Sayfaların nasıl geçtiğini anlamadığın klasik macera.','{orta,dunya_klasigi}','🗺️','ikisi',470,true),
('Tom Sawyer''ın Maceraları','Mark Twain','1876',250,290,'Mississippi kıyısında yaramaz bir çocuğun yazı. Çitin boyanmasını oyuna çevirdiği bölüm, sıkıcı bir işe nasıl bakılabileceğini anlatan en iyi sahnelerden.','{orta,dunya_klasigi}','🎣','lgs',480,true),
('Denizler Altında Yirmi Bin Fersah','Jules Verne','1870',450,520,'Kaptan Nemo''nun denizaltısında dünyanın altını dolaşmak. Bilimin merakla birleştiği uzun bir yolculuk; tatil kitabı.','{uzun,dunya_klasigi,bilim,tatil_icin}','🐙','ikisi',490,true),
('Seksen Günde Devrialem','Jules Verne','1872',250,290,'Dakikası dakikasına plan yapan bir İngiliz, bir iddia uğruna dünyayı dolaşır. Programla yaşayan bir öğrenci için keyifli bir ayna.','{orta,dunya_klasigi}','🎈','ikisi',500,true),
('Küçük Kadınlar','Louisa May Alcott','1868',450,520,'Dört kız kardeşin büyüme hikâyesi. Her biri başka bir hayali kovalar; aile içinde kendin olmayı sıcak bir dille anlatır.','{uzun,dunya_klasigi,tatil_icin}','🎹','ikisi',510,true),
('Oliver Twist','Charles Dickens','1838',400,460,'Yetimhaneden Londra sokaklarına düşen bir çocuk. Zor şartlarda bile iyi kalmanın mümkün olduğunu gösteren klasik.','{uzun,dunya_klasigi,tatil_icin}','🎩','ikisi',520,true),
('Çocuk Kalbi','Edmondo De Amicis','1886',300,350,'Bir öğrencinin okul yılı boyunca tuttuğu günlük. Arkadaşlık, öğretmen, aile; LGS''ye hazırlanan biri kendini sayfalarda bulur.','{orta,dunya_klasigi}','❤️','lgs',530,true),
('Alice Harikalar Diyarında','Lewis Carroll','1865',150,170,'Tavşan deliğinden düşen bir kızın mantığın ters döndüğü dünyası. Yazarı bir matematikçi; kelime oyunlarıyla dolu kısa bir kitap.','{kisa,dunya_klasigi}','🐇','lgs',540,true),
('Gulliver''in Gezileri','Jonathan Swift','1726',350,400,'Cüceler ülkesinden devler ülkesine bir yolculuk. Çocuk kitabı sanılır, aslında insanların küçük kavgalarıyla alay eden keskin bir hiciv.','{uzun,dunya_klasigi,tatil_icin}','🧭','ikisi',550,true),
('Kendime Düşünceler','Marcus Aurelius','180',180,210,'Bir Roma imparatorunun yalnız kendisi için tuttuğu notlar. Her sayfası ayrı okunabilir; sabah bir paragraf okuyup güne başlamak için.','{orta,felsefe}','🏛️','yks',560,true),
('Hayatın Kısalığı Üzerine','Seneca','49',60,70,'Hayat kısa değil, biz onu kısaltıyoruz, der Seneca. Zamanını nereye harcadığını sorgulatan kısa bir mektup; tek oturuşta biter.','{kisa,felsefe,tek_oturusta}','🌱','yks',570,true),
('Çalıkuşu','Reşat Nuri Güntekin','1922',450,520,'İstanbul''dan Anadolu''ya öğretmen olarak giden Feride''nin hikâyesi. Uzun ama akıcı; tatilde elden bırakılmayan romanlardan.','{uzun,turk_edebiyati,tatil_icin}','🪶','ikisi',580,true),
('Sinekli Bakkal','Halide Edib Adıvar','1936',400,460,'İstanbul''un bir mahallesinde büyüyen Rabia''nın kendi sesini bulması. Türk romanının temel taşlarından biri.','{uzun,turk_edebiyati,tatil_icin}','🏘️','yks',590,true),
('Kuyucaklı Yusuf','Sabahattin Ali','1937',250,290,'Ege''de bir kasabada büyüyen Yusuf''un doğruluk ile düzen arasında sıkışması. Kürk Mantolu Madonna''yı sevenin sıradaki kitabı.','{orta,turk_edebiyati}','🌿','yks',600,true),
('Aylak Adam','Yusuf Atılgan','1959',190,220,'İstanbul sokaklarında hep aradığı birini bekleyen genç bir adam. Kısa, modern ve kafanda uzun süre kalan bir roman.','{orta,turk_edebiyati}','🚶','yks',610,true),
('Eylül','Mehmet Rauf','1901',300,350,'Türk edebiyatının ilk psikolojik romanı. Olaydan çok duyguyu anlatır; edebiyat sorularında sık geçen bir dönemi tanımak için.','{orta,turk_edebiyati}','🌧️','yks',620,true),
('Kiralık Konak','Yakup Kadri Karaosmanoğlu','1922',250,290,'Bir konakta üç kuşak: dede, baba, torun. Değişen İstanbul''u bir ailenin içinden anlatır; Yaban''ı okuyana tanıdık bir kalem.','{orta,turk_edebiyati}','🏚️','yks',630,true),
('Saatleri Ayarlama Enstitüsü','Ahmet Hamdi Tanpınar','1961',380,440,'Saatleri ayarlamak için kurulan ve hiçbir işe yaramayan bir kurum. Türk edebiyatının en zekice yazılmış romanlarından; tatilde sindirerek okunur.','{uzun,turk_edebiyati,tatil_icin}','🕰️','yks',640,true),
('İnce Memed','Yaşar Kemal','1955',430,500,'Çukurova''da ağaya karşı dağa çıkan bir gencin destanı. Sayfalar Toroslar''ın kokusunu taşır; uzun bir tatilde başlanacak kitap.','{uzun,turk_edebiyati,tatil_icin}','🏔️','yks',650,true),
('Dede Korkut Hikâyeleri','Anonim',null,200,230,'Oğuz boylarının on iki hikâyesi. Her biri ayrı okunur, dili sadeleştirilmiş baskılarda hiç zorlanmadan ilerlenir; edebiyat derslerinde de karşına çıkar.','{orta,turk_edebiyati,oyku}','🏹','ikisi',660,true),
('Seçme Hikâyeler','Ömer Seyfettin',null,200,230,'Kaşağı, Pembe İncili Kaftan, Forsa... Her biri on dakikalık, sonu hep bir çarpıcı dönüşle biten öyküler. Okuma alışkanlığına başlamak için ideal.','{orta,turk_edebiyati,oyku}','🗡️','ikisi',670,true),
('Araba Sevdası','Recaizade Mahmut Ekrem','1896',250,290,'Her şeyi gösteriş için yapan Bihruz Bey''in komik halleri. İlk realist romanlarımızdan; gülerek okunur.','{orta,turk_edebiyati}','🐎','yks',680,true),
('Mai ve Siyah','Halit Ziya Uşaklıgil','1897',300,350,'Büyük hayaller kuran genç bir şairin hayatla sınanması. Hayallerle gerçeğin arasındaki mesafeyi anlatan bir Servet-i Fünun romanı.','{orta,turk_edebiyati}','🖋️','yks',690,true),
('Bereketli Topraklar Üzerinde','Orhan Kemal','1954',350,400,'Köyden Çukurova''ya iş aramaya gelen üç arkadaş. Emeğin, umudun ve dayanışmanın romanı.','{uzun,turk_edebiyati,tatil_icin}','🌾','yks',700,true),
('Alemdağ''da Var Bir Yılan','Sait Faik Abasıyanık','1954',150,170,'Sait Faik''in son öyküleri. Bir sayfada bir dünya kurar; Semaver''i sevdiysen buradan devam.','{kisa,turk_edebiyati,oyku}','🐍','yks',710,true),
('Zübük','Aziz Nesin','1961',250,290,'Kurnaz bir adamın kasabada nasıl yükseldiğini anlatan güldüren bir roman. Ağır bir haftanın ardından iyi gelir.','{orta,turk_edebiyati}','😄','ikisi',720,true),
('Yaprak Dökümü','Reşat Nuri Güntekin','1930',200,230,'Dürüst bir babanın, değişen şehirde ailesinin dağılışını izlemesi. Kısa, sade ve tanıdık bir aile hikâyesi.','{orta,turk_edebiyati}','🍂','ikisi',730,true),
('Kozmos','Carl Sagan','1980',400,460,'Evrenin hikâyesini bir bilim insanı değil bir anlatıcı gibi anlatır. Fizik ve kimya konularının neden önemli olduğunu gösteren, merak uyandıran bir kitap.','{uzun,bilim,tatil_icin}','🌌','yks',740,true),
('Zamanın Kısa Tarihi','Stephen Hawking','1988',230,270,'Büyük patlama, kara delikler, zamanın yönü. Neredeyse hiç formül kullanmadan evrenin nasıl işlediğini anlatır.','{orta,bilim}','🕳️','yks',750,true),
('Eminim Şaka Yapıyorsunuz Bay Feynman','Richard P. Feynman','1985',380,440,'Nobel''li bir fizikçinin kasa kilidi açmaktan bongo çalmaya uzanan anıları. Merakla öğrenmenin en eğlenceli kitabı.','{uzun,bilim}','🥁','yks',760,true),
('İnsanın Anlam Arayışı','Viktor E. Frankl','1946',160,190,'Bir psikiyatristin toplama kampında gördükleri ve oradan çıkardığı ders: insan, bir "neden"i varsa her "nasıl"a dayanabilir. Hedefini unutan her öğrenciye.','{kisa,psikoloji}','🕯️','yks',770,true),
('Sophie''nin Dünyası','Jostein Gaarder','1991',550,630,'Posta kutusuna gelen gizemli mektuplarla felsefe tarihine yolculuk. Roman gibi okunan bir felsefe kitabı; uzun tatil için.','{uzun,felsefe,tatil_icin}','📬','ikisi',780,true),
('Fermat''nın Son Teoremi','Simon Singh','1997',330,380,'Üç yüz elli yıl çözülemeyen bir problem ve onu yedi yıl gizlice çalışarak çözen matematikçi. Tek bir soruya sabırla odaklanmanın hikâyesi.','{uzun,bilim}','🧮','yks',790,true),
('Einstein''ın Rüyaları','Alan Lightman','1992',150,170,'Her bölümde zamanın başka türlü aktığı bir dünya. Bir fizikçinin yazdığı şiir gibi kısa bir kitap; her gece bir bölüm.','{kisa,bilim}','🕐','ikisi',800,true),
('Sayı Şeytanı','Hans Magnus Enzensberger','1997',260,300,'Matematikten korkan bir çocuğun rüyasına her gece bir şeytan gelir ve sayıların oyunlarını gösterir. Matematikle arası kötü olan için.','{orta,bilim}','🔢','lgs',810,true),
('Bir Matematikçinin Savunması','G. H. Hardy','1940',120,140,'Büyük bir matematikçi, ömrünün sonunda matematiğin neden güzel olduğunu anlatır. Kısa ve dürüst bir deneme.','{kisa,bilim}','📐','yks',820,true);

insert into public.haftalik_soz (metin, kaynak, dogrulandi, tema, emoji, sira, aktif) values
('Sabrın sonu selamettir.','Atasözü',true,'sabir','🌱',270,true),
('Sabırla koruk helva olur.','Atasözü',true,'sabir','🍇',280,true),
('Acele işe şeytan karışır.','Atasözü',true,'sabir','🐢',290,true),
('Zihne dinlenme verilmeli; dinlenen zihin daha iyi ve daha keskin kalkar.','Seneca, Ruh Dinginliği Üzerine',true,'dinlenme','🛌',300,true),
('Dinlenmek çalışmadan çalınan zaman değil, çalışmanın bir parçasıdır.',null,false,'dinlenme','☕',310,true),
('Hep denedin. Hep yenildin. Olsun. Yine dene. Yine yenil. Daha iyi yenil.','Samuel Beckett',true,'hata','🔁',320,true),
('Bilmemek ayıp değil, öğrenmemek ayıp.','Atasözü',true,'hata','📖',330,true),
('Hatasız kul olmaz.','Atasözü',true,'oz_sefkat','🤲',340,true),
('Kendine, en yakın arkadaşına konuştuğun gibi konuş.',null,false,'oz_sefkat','💬',350,true),
('Emek olmadan yemek olmaz.','Atasözü',true,'emek','🍞',360,true),
('İşleyen demir ışıldar.','Atasözü',true,'emek','⚒️',370,true),
('Her yerde olan, hiçbir yerde değildir.','Seneca, Lucilius''a Mektuplar',true,'odak','🎯',380,true),
('Bütün insanlar doğaları gereği bilmek ister.','Aristoteles, Metafizik',true,'merak','🔭',390,true),
('Başlangıç, bütünün yarısıdır.','Aristoteles, Politika',true,'baslangic','🚪',400,true),
('Damlaya damlaya göl olur.','Atasözü',true,'sureklilik','💧',410,true),
('Deniz durgunken herkes dümenci olur.',null,false,'cesaret','⛵',420,true),
('Bugün yalnızca bir adım. Yarını yarın düşünürüz.',null,false,'baslangic','👣',430,true),
('Korktuğun iş, çoğu zaman düşündüğünden küçüktür.',null,false,'cesaret','🦁',440,true);
